.browserslistrc
.eslintrc.js
.gitignore
.travis.yml
__tests__/.eslintrc.js
__tests__/Keys.test.ts
examples/.eslintrc.js
examples/transfer-crypto.js
jest.config.js
package.json
src/Client.ts
src/Keys.ts
src/Transaction.ts
src/TransactionBuilder.ts
src/util.ts
yarn.lock

Make keystore test use the existing test key instead of generating a new one

---

.browserslistrc
.eslintrc.js
.gitignore
.travis.yml
__tests__/.eslintrc.js
__tests__/Keys.test.ts
examples/.eslintrc.js
examples/transfer-crypto.js
jest.config.js
package.json
src/Client.ts
src/Keys.ts
src/Transaction.ts
src/TransactionBuilder.ts
src/util.ts
yarn.lock

I made some opinionated decisions about rules and documented them.

add ESLint config and fix lint errors

---

.browserslistrc
.eslintrc.js
.gitignore
.travis.yml
__tests__/.eslintrc.js
__tests__/Keys.test.ts
examples/.eslintrc.js
examples/transfer-crypto.js
jest.config.js
package.json
src/Client.ts
src/Keys.ts
src/Transaction.ts
src/TransactionBuilder.ts
src/util.ts
yarn.lock

* wasn't incrementing `attempt`
* was throwing on `UNKNOWN` when first encountered (`Array.indexOf() > 0` instead of `Array.indexOf() >= 0`/`Array.includes()`)
* wasn't sleeping between attempts
* wasn't calculating transaction expiry properly

Fix `Transaction.waitForReceipt()`

---

.browserslistrc
.eslintrc.js
.gitignore
.travis.yml
README.md
__tests__/.eslintrc.js
__tests__/Keys.test.ts
examples/.eslintrc.js
examples/transfer-crypto.js
index-web.ts
jest.config.js
package.json
src/Client.ts
src/Keys.ts
src/Transaction.ts
src/TransactionBuilder.ts
src/account/AccountCreateTransaction.ts
src/account/CryptoTransferTransaction.ts
src/util.ts
tsconfig.json
yarn.lock

closes #5
this should be a bump to `0.2.0`

use bignumber.js instead of ESNext `bigint`

---

__tests__/Keys.test.ts
index-web.ts
src/Keys.ts
src/account/AccountCreateTransaction.ts

implement threshold keys

---

package.json

Signed-off-by: Ryan Leckey <ryan@launchbadge.com>
---
@kenthejr @abonander This is going to get annoying I think unless we can think of how to auto-publish master I think. Then we can have "Prepare version" PRs. Heh.

Release v0.2.0 (it was already released, this just tells the repo that it was)

---

index-node.ts
package.json

move `grpc-web-node-http-transport` to regular deps

---

examples/create-account.js
examples/get-account-balance.js
examples/transfer-crypto.js
examples/yarn.lock
exports.ts
index-node.ts
index-web.ts
package.json
scripts/compile-protos.sh
src/BaseClient.ts
src/Transaction.ts
src/TransactionBuilder.ts
src/account/AccountCreateTransaction.ts
src/account/CryptoTransferTransaction.ts
src/util.ts
yarn.lock

~~need to make sure this still works in a browser but it should~~ yep, with no changes necessary

support direct connection to Hedera in Node.js

---

.gitignore
package.json
yarn.lock

Also bumped all dependencies to latest

Release v0.3.0

---

exports.ts
src/BaseClient.ts
src/Transaction.ts
src/TransactionBuilder.ts
src/account/CryptoTransferTransaction.ts
src/typedefs.ts
src/util.ts

export more types

---

__tests__/.eslintrc.js
__tests__/Transaction.test.ts
src/BaseClient.ts
src/Transaction.ts
src/TransactionBuilder.ts
src/util.ts

implement (de)serialization for transactions

---

__tests__/Keys.test.ts
src/Keys.ts
yarn.lock

ensure generateMnemonic() generates 24 word phrases

---

__tests__/Transaction.test.ts
index-node.ts
index-web.ts
src/BaseClient.ts
src/Transaction.ts
src/TransactionBuilder.ts

protect unstable APIs with symbols

---

__tests__/Keys.test.ts

test that signing still works for derived keys (sanity check)

---

__tests__/Keys.test.ts

test that `Ed25519PrivateKey.fromKeystore()` with wrong password rejects

---

exports.ts

reexport `MnemonicResult`

---

__tests__/Hbar.test.js.ts
__tests__/util.test.ts
src/BaseClient.ts
src/Hbar.ts
src/TransactionBuilder.ts
src/account/AccountCreateTransaction.ts
src/account/CryptoTransferTransaction.ts
src/errors.ts
src/typedefs.ts
src/util.ts

also document `number | BigNumber` as a `Tinybar` type and explain supported ranges
after merge I'll rebase #49 onto this one.

improve `Hbar` and tinybar range checking throughout SDK

---

__tests__/util.test.ts
examples/get-account-info.js
examples/yarn.lock
exports.ts
patches/CryptoCreate.proto.patch
patches/CryptoGetInfo.proto.patch
patches/ResponseHeader.proto.patch
src/BaseClient.ts
src/Hbar.ts
src/QueryBuilder.ts
src/TransactionBuilder.ts
src/account/AccountCreateTransaction.ts
src/account/CryptoTransferTransaction.ts
src/account/account-info.ts
src/errors.ts
src/proto/CryptoCreate.proto
src/proto/CryptoGetInfo.proto
src/proto/ResponseHeader.proto
src/util.ts

implement AccountInfoQuery

---

exports.ts

reexport the new error types

---

__tests__/Keys.test.ts
src/Keys.ts

add ability to get raw/unprefixed key strings

---

index-web.ts

The comment and the URL were both significantly outdated.

update grpc-web testnet proxy

---

__tests__/util.test.ts
src/BaseClient.ts
src/TransactionBuilder.ts
src/account/CryptoTransferTransaction.ts
src/account/account-info.ts
src/typedefs.ts
src/util.ts

accept more types for account/contract/file/transaction IDs

---

src/account/AccountCreateTransaction.ts

AccountCreateTransaction: don't require a nonzero initial balance

---

exports.ts

export ID types and normalization functions

---

exports.ts

Fix normalize* reexports

---

__tests__/Hbar.test.js.ts
__tests__/Hbar.test.ts
src/Hbar.ts

closes #57 
This exposes the following comparison functions from bigNumber and adds more tests.
- `isLessThan`
- `isGreaterThan`
- `isLessThanOrEqualTo`
- `isGreaterThanOrEqualTo`
- `isZero`
- `isPositive`
Also adds a constant `ZERO` and a `zero` factory function.

Improvements to the Hbar class

---

src/crypto/Ed25519PrivateKey.ts

Signed-off-by: josh <josh@launchbadge.com>

Add Key Length to Invalid Private Key Error

---

src/TransactionReceipt.ts
src/file/FileCreateTransaction.ts

Set a default expiration time when a FCT is created to the required time.

Fix TransactionReceipt and setExpirationDate on FileCreateTransaction

---

src/exports.ts

reexport `TransactionRecord`/`TransactionReceipt`

---

src/account/AccountCreateTransaction.ts

Checks for positive value only now.

Remove non-zero initial balance check on account creation

---

README.md

Pre-v1 are considered not-ready for production. Version 1.0.0 will be set once the repo is feature complete and CI testing is stabilized.
Signed-off-by: Ken A <ken@hedera.com>

Added disclaimer to README

---

__tests__/account/AccountUpdateTransaction.test.ts
src/Tinybar.ts
src/account/AccountUpdateTransaction.ts
src/exports.ts

- Add Serialization test for AUT
- Export AUT
- Use proto `UInt64Value` instead of `uint`

Implement AccountUpdateTransaction

---

__tests__/Keys.test.ts
src/crypto/KeyList.ts
src/crypto/ThresholdKey.ts
src/exports.ts

unify proto import convention with ThresholdKey

add and test KeyList

---

src/QueryBuilder.ts

Should prevent #105 in the future

Type check arguement in `Transaction.setPayment`

---

src/Transaction.ts
src/crypto/Ed25519PublicKey.ts

check for duplicate keys in Transaction.sign()

---

__tests__/TransactionReceiptQuery.test.ts
__tests__/TransactionRecordQuery.test.ts
__tests__/account/AccountBalanceQuery.test.ts
__tests__/contract/ContractBytecodeQuery.test.ts
__tests__/contract/ContractCallQuery.test.ts
__tests__/contract/ContractFunctionParams.test.ts
__tests__/contract/ContractFunctionResult.test.ts
__tests__/contract/ContractInfoQuery.test.ts
__tests__/contract/ContractRecordsQuery.test.ts
__tests__/contract/ContractUpdateTransaction.test.ts
__tests__/file/FileContentsQuery.test.ts
__tests__/file/FileInfoQuery.test.ts
src/contract/ContractFunctionParams.ts
src/contract/ContractFunctionResult.ts
src/contract/ContractUpdateTransaction.ts
src/file/FileCreateTransaction.ts

- Make `name` nullable in `ContractFunctionParams._build()`
- Add tests for unnamed parameters

Fix build errors and update `ContractFunctionParams`

---

__tests__/Keys.test.ts
__tests__/account/AccountCreateTransaction.test.ts
__tests__/contract/ContractCreateTransaction.test.ts
__tests__/file/FileCreateTransaction.test.ts
src/Hbar.ts
src/TransactionBuilder.ts
src/account/AccountCreateTransaction.ts
src/contract/ContractCallQuery.ts
src/contract/ContractCreateTransaction.ts
src/file/FileCreateTransaction.ts

Add `.setTransactionId` to *CreateTransation

---

examples/create-pub-sub.js
examples/yarn.lock
src/consensus/ConsensusTopicCreateTransaction.ts
src/errors/TinybarValueError.ts
src/mirror/MirrorConsensusTopicResponse.ts

- Update `ConsensusCreateTopicTransaction` to set auto
renew period to the correct value in constructor.

Fix HCS pub sub example

---

src/TransactionReceiptQuery.ts

Fix f_shouldRetry()` logic for `TransactionReceiptQuery`

---

__tests__/Hbar.test.ts
src/Hbar.ts

Add test for `Hbar.multipliedBy()`

Fix `Hbar.multipliedBy()`

---

examples/confirmation-mechanisms.js
examples/consensus-pub-sub-with-submit-key.js
examples/consensus-pub-sub.js
examples/create-account.js
examples/create-consensus-topic.js
examples/create-file.js
examples/create-threshold-account.js
examples/delete-account.js
examples/delete-file.js
examples/get-account-info.js
examples/get-file-contents.js
examples/hedera-client.js
examples/multi-party-transfer.js
examples/transfer-crypto.js

run eslint against /examples

---

__tests__/unit/Keys.test.ts
__tests__/unit/pkcs.test.ts
src/crypto/Ed25519PrivateKey.ts
src/crypto/der.ts
src/crypto/pkcs.ts
src/errors/BadKeyError.ts

Made `fromPem()` async (should be fine since I don't think we've released this yet).
Closes #208 

Ed25519PrivateKey: implement PEM decryption

---

.editorconfig
src/consensus/ConsensusTopicId.ts
src/consensus/ConsensusTopicInfoQuery.ts
src/mirror/BaseMirrorConsensusTopicQuery.ts

Note: This PR also added `.editorconfig` file. This is only here because creating a new  PR just for that seems a little much. However, if one of the reviewers thinks is necessary I move it to it's own PR.

Update `*.setTopicId()` to support `ConsensusTopicIdLike`

---

CHANGELOG.md

Update CHANGELOG for `Unreleased` SDK version

---

.gitignore
__tests__/e2e/contract/Contract.test.ts
src/contract/ContractFunctionParams.ts

Fix `ContractFunctionParams.addBytes32Array()` selector

---

package.json
src/Transaction.ts
src/crypto/Ed25519PrivateKey.ts

Reverts hashgraph/hedera-sdk-js#272

Revert "Drop stablelib/base64 as there is already a decoder impl present here"

---

examples/multi-sig-offline.js

* creates a multi-sig account
* creates a crypto transfer transaction
* requests signatures from other key holders
* signs the transaction with all signatures
* executes

Example creating a multi-sig account, and signing a transaction offline

---

src/transaction/Transaction.js

Signed-off-by: derdis14 <78613993+derdis14@users.noreply.github.com>

fix: added frozen requirement check before signing

---

README.md

Signed-off-by: SimiHunjan <simi.hunjan.k@gmail.com>

v1 deprecation notice

---

src/Hbar.js

feat: Hbar.fromTinybars now accepts string, added Hbar.toBigNumber

---

src/token/TokenInfo.js

fix: added documentation and @readonly to tokenMemo field

---

packages/cryptography/test/unit/key.js

fix: added a verified key check to keystore test

---

package.json
src/Executable.js
src/query/CostQuery.js
src/query/Query.js
src/transaction/Transaction.js
src/transaction/TransactionReceiptQuery.js
src/transaction/TransactionRecordQuery.js

fix: `TransactionReceiptQuery` error handling

---

src/channel/NodeMirrorChannel.js

fix: add basic client side TLS support for mirror node connections

---

src/Executable.js
src/array.js
src/client/Client.js
src/query/CostQuery.js
src/query/Query.js
src/transaction/SignatureMap.js
src/transaction/Transaction.js
src/transaction/TransactionHashMap.js
test/integration/ClientIntegrationTest.js

feat: add sign-on-demand functionaltiy that is disabled by default

---

CHANGELOG.md
src/Hbar.js
src/long.js
test/unit/Hbar.js

Resolves: #426 
Resolves: #428

Update `Hbar` to use `BigNumber` internally and implement `Hbar.toString(HbarUnit)`

---

src/token/TokenMintTransaction.js
test/integration/TokenMintIntegrationTest.js

fix: fixed TokenMineTransaction to|fromBytes, added a test

---

__tests__/unit/Mnemonic.test.ts
src/crypto/Mnemonic.ts
src/crypto/util.ts

fix: legacy derive, and mnemonic 3derive, added tests

---

src/FeeComponents.js
src/FeeData.js
src/FeeSchedule.js
src/FeeSchedules.js
src/RequestType.js
src/SubType.js
src/TransactionFeeSchedule.js

Signed-off-by: andvara-naut <dalton.kaua@launchbadge.com>

feat: support file parsing 0.0.111

---

src/token/TokenCreateTransaction.js

Read issues
Closes: #457 
Closes: #461
Testing will be done in a separate PR
**Checklist**

fix: remove `*.addCustomFee()` and implement `setFeeScheduleKey()`

---

test/integration/TokenNftIntegrationTest.js

test: add NFT tests which expect certain status codes

---

src/Executable.js
src/NetworkName.js
src/client/Client.js
src/client/Network.js
test/integration/ClientIntegrationTest.js
test/integration/client/browser.js
test/integration/client/index.js

feat: add `Client.[set|get]NetworkName()` accessors

---

.github/dependabot.yml

I believe the packages folder should get updated automatically via the main package.json since it's a child dependency.
**Checklist**

Add automated Dependabot updates

---

.github/workflows/main.yml
.github/workflows/testnet.yml
CONTRIBUTING.md
README.md

* Fix CI not running
* Fix references to master
**Checklist**

Fix CI & rename references to master

---

packages/proto/src/index.d.ts
packages/proto/src/index.js
packages/proto/src/proto/CustomFees.proto
packages/proto/src/proto/Freeze.proto
packages/proto/src/proto/ResponseCode.proto
pnpm-lock.yaml

chore: update protobufs

---

package.json
pnpm-lock.yaml
src/Status.js
src/client/Client.js
src/exports.js
src/system/FreezeTransaction.js
src/token/AssessedCustomFee.js
src/token/CustomFractionalFee.js
src/token/CustomRoyaltyFee.js
src/token/FeeAssessmentMethod.js
src/token/TokenCreateTransaction.js
src/token/TokenFeeScheduleUpdateTransaction.js
src/token/TokenInfo.js
test/integration/CustomFeesIntegrationTest.js
test/integration/client/index.js

feat: add royalty fees, update `FreezeTransaction`, update `Status`

---

CHANGELOG.md
src/token/TokenNftInfoQuery.js

feat: remove support for querying nft info by account ID and token ID

---

test/integration/CustomFeesIntegrationTest.js
test/integration/TokenBurnIntegrationTest.js
test/integration/TokenDissociateIntegrationTest.js
test/integration/TokenMintIntegrationTest.js
test/integration/TokenTransferIntegrationTest.js
test/integration/TokenUpdateIntegrationTest.js
test/integration/client/index.js

test: add tests for new response codes

---

src/topic/TopicMessageSubmitTransaction.js
src/util.js
test/unit/TopicMessageSubmitTransaction.js

TopicMessageSubmitTransaction.setMessage() silent error changed to throw when passed non string - uint8array or undefined.
Linked Issue: #624 
Signed-off-by: andvara-naut <dalton.kaua@launchbadge.com>

fix: silent set message error

---

packages/proto/src/proto/contract_call_local.proto
packages/proto/src/proto/contract_update.proto
src/contract/ContractCallQuery.js
src/contract/ContractUpdateTranscation.js

fix: deprecate maxResultSize|FileID

---

src/ObjectMap.js
test/unit/PublicKey.js

Fixes [#711](https://github.com/hashgraph/hedera-sdk-js/issues/711)
**Checklist**

fix: `PublicKey.verifyTransaction()`

---

src/contract/ContractExecuteTransaction.js

feat: ContractExecuteTransaction.setFunctionParameters return statement

---

packages/proto/src/proto/response_code.proto
src/Status.js

feat: gas-proto-code

---

.github/workflows/browser.yml
.github/workflows/build.yml
.github/workflows/common_js.yml
.github/workflows/main.yml
.github/workflows/previewnet.yml
.github/workflows/react_native.yml
.github/workflows/testnet.yml
CHANGELOG.md
pnpm-lock.yaml
src/ManagedNode.js
src/MirrorNode.js
src/Node.js
src/client/ManagedNetwork.js
src/client/MirrorNetwork.js
src/client/Network.js
src/client/WebClient.js
test/integration/client/WebIntegrationTestEnv.js

Clean up network and fix `WebClient` failing to construct `MirrorNetwork`

---

CHANGELOG.md
pnpm-lock.yaml
src/EntityIdHelper.js
src/Timestamp.js
src/account/AccountId.js
src/account/TransferTransaction.js
src/contract/ContractId.js
src/file/FileId.js
src/schedule/ScheduleId.js
src/token/TokenId.js
src/topic/TopicId.js
src/transaction/TransactionId.js
test/unit/TransferTransaction.js

feat: order protobuf transfers

---

src/account/TransferTransaction.js
src/token/NftId.js
src/util.js
test/unit/TransferTransaction.js

fix: nftid support for TransferTransaction

---

src/channel/Channel.js
src/util.js

Fix-ups to https://github.com/hashgraph/hedera-sdk-js/pull/782.
Fixes https://github.com/hashgraph/hedera-sdk-js/pull/782#discussion_r760681099
Fixes https://github.com/hashgraph/hedera-sdk-js/pull/782#pullrequestreview-820947424
This introduces a new error in `Channel.js`, please recheck.
**Checklist**

fix: improvements to DataView logic

---

packages/proto/src/proto/basic_types.proto
packages/proto/src/proto/response_code.proto
packages/proto/src/proto/transaction_get_receipt.proto
packages/proto/src/proto/transaction_get_record.proto
packages/proto/src/proto/transaction_record.proto

feat: protobuf changes for hip-206

---

packages/proto/src/proto/response_code.proto
src/Status.js
src/account/AccountId.js
src/transaction/TransactionId.js
src/transaction/TransactionReceiptQuery.js
src/transaction/TransactionRecord.js
src/transaction/TransactionRecordQuery.js
test/unit/TokenPauseTransaction.js
test/unit/TokenUnpauseTransaction.js
test/unit/TransactionId.js

feat: HIP-206

---

packages/cryptography/src/EcdsaPrivateKey.js
packages/cryptography/src/EcdsaPublicKey.js
packages/cryptography/src/Ed25519PrivateKey.js
packages/cryptography/src/Ed25519PublicKey.js
packages/cryptography/src/PrivateKey.js
packages/cryptography/src/PublicKey.js
pnpm-lock.yaml

#827
This PR has to be separate from the other PR since this is required to be released before the other PR's CI passes.
**Checklist**

Fix: add key type helper

---

packages/proto/src/proto/basic_types.proto
packages/proto/src/proto/response_code.proto
src/Status.js

feat: HIP-31 proto changes

---

src/file/FileId.js
src/topic/TopicId.js

Added to and from solidity methods from file ID and topic ID
Fixes # https://github.com/hashgraph/hedera-sdk-js/issues/848
**Checklist**

Add to and from solidity

---

src/Status.js

added new status codes to Status.js

---

examples/hts-nftP1-fee-create-mint-burn-associate-transfer.js
examples/hts-nftP2-kyc-upate-schedule.js
examples/hts-nftP3-pause-freeze-wipe-delete.js

Added example file hts-nftP1-fee-create-mint-burn-associate-transfer.js to support blog post on NFTs with HTS

---

package.json

Signed-off-by: Keira Black <keirablack@Keiras-MacBook-Pro.local>
This should resolve the expo dependency warning. 
Fixes # 969
**Checklist**

Added optional dependency expo.

---

CHANGELOG.md
src/transaction/Transaction.js
src/util.js
test/unit/Transaction.js
test/unit/util.js

feat: validate transaction bodies

---

CHANGELOG.md
src/EntityIdHelper.js
src/LedgerId.js
src/client/ManagedNetwork.js
test/unit/ChecksumValidation.js

fix: checksums

---

src/account/AccountAllowanceAdjustTransaction.js

I change hedera-sdk-js/src/account/AccountAllowanceAdjustTransaction.js  `
line 361 'revokeTokenNftAllowance' function
Because id is frozen object, id.serial can not change.
https://github.com/hashgraph/hedera-sdk-js/issues/1030
Fixes #
Assign NftId to new NftId Object
**Checklist**

revokeTokenNftAllowance bug fix(issue/1030)

---

CHANGELOG.md
package.json
pnpm-lock.yaml
src/contract/ContractFunctionResult.js

This PR modifies `ContractFunctionResult` to include `gas`, `amount`, and `functionParameters`
Fixes #
[HIP-206](https://github.com/hashgraph/hedera-sdk-js/issues/1009#issue-1172564681)
**Checklist**

feat HIP-206

---

package.json
pnpm-lock.yaml
src/Provider.js
src/Signer.js
src/client/ManagedNetwork.js
src/util.js

This PR modifies several files in order to satisfy the SonarCloud issues.
Fixes #1019 
**Checklist**

Review SonarCloud Issues

---

src/schedule/ScheduleCreateTransaction.js
src/schedule/ScheduleInfo.js

This PR modifies ScheduleCreateTransaction and ScheduleInfo in order to support expiration enhancements to make contracts more flexible.
* Adds waitForExpiry, expirationTime
#1075 
This is kind of an updated copy of another pr, HIP-423-enhancescheduledcreatetransactions for this same issue, so whoever closes this out should close that out as well.
**Checklist**
- [X ] Documented (Code comments, README, etc.)
- [X ] Tested (unit, integration, etc.)

Updated fields for enhancing scheduled transactions.

---

CHANGELOG.md
package.json
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/Status.js
src/contract/ContractCreateFlow.js
src/contract/ContractCreateTransaction.js
src/contract/ContractDeleteTransaction.js
src/contract/ContractUpdateTransaction.js
src/topic/TopicUpdateTransaction.js
test/integration/ContractCreateFlowIntegrationTest.js
test/integration/ContractCreateIntegrationTest.js
test/integration/ContractUpdateIntegrationTest.js

This PR modifies the following: 
- ContractCreateTransaction.[get|set]maxAutomaticTokenAssociation
- ContractUpdateTransaction.[get|set]maxAutomaticTokenAssociation
- ContractCreateFlow.[get|set]maxAutomaticTokenAssociation
- ContractCreateFlow.[get|set]autoRenewAccountId
- Tests were added where applicable for corresponding methods already mentioned above
Fixes #1081 
**Checklist**

1081 support auto association slots for contracts

---

CHANGELOG.md
src/Signer.js
src/account/AccountInfoFlow.js
src/contract/ContractCreateFlow.js
src/transaction/TransactionResponse.js
test/unit/FileAppendMocking.js

feat: implement `*Flow.*WithSigner()` methods

---

src/EthereumTransaction.js
test/unit/EthereumTransaction.js

Signed-off-by: Keira Black <keirablack@Keiras-MacBook-Pro.local>
Fixes #
#1130 
**Checklist**
- [ n/a] Documented (Code comments, README, etc.)
- [ X] Tested (unit, integration, etc.)

Updated symbol name per bug from setCallData to setCallDataFileId

---

package.json
pnpm-lock.yaml
src/Cache.js
src/Executable.js
src/Timestamp.js
src/sync.js
src/sync.native.js
src/transaction/Transaction.js
test/unit/EthereumFlowMocking.js
vite.config.cjs

feat: implement time drift syncing

---

examples/pnpm-lock.yaml
examples/staking-example-1.js
examples/staking-example-2.js
src/account/AccountUpdateTransaction.js

feat: implement staking examples

---

examples/package.json
examples/pnpm-lock.yaml
examples/schedule-example.js
src/schedule/ScheduleCreateTransaction.js
src/schedule/ScheduleInfo.js

feat: implement long term schedule transaction example

---

src/Executable.js
src/query/Query.js
src/transaction/Transaction.js

feat: log protobufs being sent and received

---

CHANGELOG.md
src/FeeDataType.js
test/unit/FeeDataType.js

test: `FeeDataType` has all variants of `SubType`

---

CHANGELOG.md
src/topic/TopicMessage.js
test/unit/FeeDataType.js

feat: implement `TopicMessage.initialTransactionId`

---

examples/account-alias.js
examples/account-allowance.js
examples/create-account.js
examples/create-simple-contract.js
examples/create-stateful-contract.js
examples/create-topic.js
examples/delete-account.js
examples/file-append-chunked.js
examples/get-account-balance.js
examples/get-account-info.js
examples/get-exchangerates.js
examples/schedule-example.js
examples/scheduled-transaction-multi-sig-threshold.js
examples/sign-transaction.js
examples/staking-example-1.js
examples/staking-example-2.js
examples/transfer-tokens.js

feat: update some examples to use `Wallet` instead of `Client` direclty

---

CHANGELOG.md
src/sync.js

fix: sync should use https

---

src/EthereumFlow.js

Signed-off-by: nikolay <n.atanasow94@gmail.com>
Fixes #
- https://github.com/hashgraph/hedera-sdk-js/issues/1172
**Checklist**

Add keys on FileCreateTransaction in EthereumFlow

---

examples/prng-transaction.js
package.json
packages/proto/Taskfile.yml
pnpm-lock.yaml
src/PRNGTransaction.js
src/RNGTransaction.js
src/RequestType.js
src/Status.js
src/channel/Channel.js
src/contract/ContractFunctionResult.js
src/contract/ContractStateChange.js
src/exports.js
src/transaction/TransactionRecord.js
test/unit/Status.js

This is to add example random number generation to the js sdk 
This PR modifies ... in order to support ...
Fixes #1170 #1169 
**Checklist**

Feature/1169 rngtransaction-fix and example added

---

CHANGELOG.md
src/contract/ContractFunctionResult.js
src/contract/ContractStateChange.js
src/contract/StorageChange.js
src/transaction/Transaction.js

fix: deprecate `ContractFunctionResult.stateChanges`

---

src/contract/ContractCreateFlow.js

fix: implement `ContractCreateFlow.[set|get][AutoRenewAccountId|DeclineStakingRewards]()`

---

CHANGELOG.md
src/account/AccountBalance.js

fix: deprecate `AccountBalance.[tokens|tokenDeciamls]`

---

examples/account-alias.js
examples/account-allowance.js
examples/create-account.js
examples/create-simple-contract.js
examples/create-stateful-contract.js
examples/create-topic.js
examples/delete-account.js
examples/file-append-chunked.js
examples/prng-transaction.js
examples/schedule-example.js
examples/scheduled-transaction-multi-sig-threshold.js
examples/sign-transaction.js
examples/staking-example-1.js
examples/staking-example-2.js
examples/transfer-tokens.js
src/Executable.js
src/Wallet.js
src/token/TokenCreateTransaction.js
src/transaction/Transaction.js

Fixes #1179 #1200
**Checklist**

fix: examples should sign each transaction with the wallet

---

CHANGELOG.md
src/token/TokenNftInfo.js

feat: implement `TokenNftInfo.allowanceSpenderAccountId`

---

src/contract/ContractFunctionResult.js

Signed-off-by: nikolay <n.atanasow94@gmail.com>
Fixes #1208
**Checklist**

fix: handle nullable gas and amount in ContractFunctionResult when ContractCallLocal is passed

---

.github/workflows/build.yml
.github/workflows/common_js.yml
.github/workflows/main.yml
.github/workflows/react_native.yml
Taskfile.yml
package.json
packages/proto/.eslintrc.cjs
packages/proto/Taskfile.yml
packages/proto/package.json
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/PrngTransaction.js
src/RequestType.js

fix: update `PrngTransaction` to use new `UtilPrngTransactionBody`

---

CHANGELOG.md
src/contract/ContractCreateFlow.js

feat: implement `ContractCreateFlow.sign[With]()`

---

CHANGELOG.md
src/file/FileAppendTransaction.js
test/unit/FileAppendMocking.js

chore: update `FileAppendTransaction` default chunk size

---

CHANGELOG.md
src/file/FileAppendTransaction.js
src/topic/TopicMessageSubmitTransaction.js
test/integration/CryptoTransferIntergationTest.js

fix: regression with chunked transactions `setTransactionId()` not locking list

---

packages/cryptography/src/EcdsaPrivateKey.js

Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>
Fixes #1220 
**Checklist**

ECDSA PrivateKey sometime generates less than 32 bytes raw key

---

CHANGELOG.md
src/token/TokenUpdateTransaction.js
test/unit/TokenCreateTransaction.js
test/unit/TokenUpdateTransaction.js

fix: `TokenUpdateTransaction.pauseKey`

---

src/client/NodeClient.js

This PR updates the list of nodes for Mainnet, Testnet and Previewnet.
N/A
N/A
**Checklist**

Updated node list (Mainnet, Testnet and Previewnet)

---

src/Executable.js
src/query/CostQuery.js
src/query/Query.js
src/transaction/Transaction.js

chore: remove `Executable._getNodeAccountIds()`

---

package.json
packages/cryptography/package.json

Signed-off-by: Ryan Leckey <ryan@launchbadge.com>

chore: make react-native peer dependencies optional

---

CHANGELOG.md
src/contract/ContractCreateFlow.js
test/unit/ContractCreateFlowMocking.js
test/unit/FileAppendMocking.js
test/unit/Mocker.js
test/unit/TransferTransaction.js

fix: `ContratCrateFlow.execute()` should sign all transations with any key passed to `.sign()`

---

CHANGELOG.md
Taskfile.yml
src/Cache.js
src/transaction/TransactionId.js

fix: implement `TransactionId.get[Receipt|Record]()`

---

src/LedgerId.js
src/client/NodeClient.js
test/unit/LedgerId.js
test/unit/NodeClient.js

- Add cases in `LedgerId` and `NetworkClient` for local node support.

Add `LocalProvider` support for `HEDERA_NETWORK=local-node`

---

src/Cache.js
src/contract/ContractCreateFlow.js
test/unit/ContractCreateFlowMocking.js
test/unit/Mocker.js

Fixes #1256 
Implemented fix and manually checked it works using one of our examples. Still need to add an automatic test for signature providers.
**Checklist**

fix: `ContractCreateFlow.executeWithSigner()`

---

CHANGELOG.md
package.json
packages/proto/Taskfile.yml
pnpm-lock.yaml
src/account/AccountCreateTransaction.js

feat: implement `AccountCreateTransaction.setAlias[Key|EvmAddress]()`

---

src/PrecheckStatusError.js
src/contract/ContractCallQuery.js
src/query/Query.js
src/transaction/TransactionReceiptQuery.js

Closes https://github.com/hashgraph/hedera-sdk-js/issues/1261

feat: expose contractFunctionResult on a failed call to ContractCallQuery

---

examples/account-create-with-hts.js
examples/exempt-custom-fees.js
examples/zeroTokenOperations.js

The task run with `task test:release` is fixed with this PR.
Fixes #
Linter Fixes.
**Checklist**

Fix the task test:release command

---

src/client/NodeClient.js
test/integration/AddressBookQueryTest.js
test/unit/ManagedNodeAddress.js

Update the Mainnet mirror node
Fixes #1326 
The Mainnet mirror node is changed and we use the old one
**Checklist**

Update the Mainnet mirror node and add integration test

---

common_js_test/Taskfile.yml
src/client/Client.js
src/network/AddressBookQuery.js

Signed-off-by: ochikov <ognyan@limechain.tech>
Update the network update time period to 24 hours.
Fixes #1342 
**Checklist**

Update the addressbook update to be 24 hours

---

.github/workflows/pages.yml

Add workflow for updating the docs.
Fixes #1484 
**Checklist**

Create github workflow for updating the docs

---

examples/topic-message-submit-get-all-chunks-status.js

Added an example to show how users can get all the chunks' statuses.
Fixes #1333 
**Checklist**

create example for getting all chunked messages statuses

---

CHANGELOG.md

Changelog for release

---

.babelrc.json
common_js_test/pnpm-lock.yaml
examples/pnpm-lock.yaml
examples/simple_rest_signature_provider/pnpm-lock.yaml
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/exports.js

Expose the EntitiyIdHelper for external usage.
Fixes #1568 
**Checklist**

add export for EntityIdHelper

---

src/client/ManagedNetwork.js

Fix an issue regarding the way we get a node for execution based on whether or not the list is locked
Fixes #
**Checklist**

Fix conditions in getNode

---

RELEASE.md

added release doc

---

.github/dependabot.yml
packages/proto/package.json
packages/proto/pnpm-lock.yaml

Remove unnecessary dependencies in devDependencies, check other packages for similar packages and release stable version of proto package
Fixes #1716 
**Checklist**

Fix dependencies

---

examples/contract-nonces.js
package.json
pnpm-lock.yaml
src/contract/ContractFunctionResult.js
src/contract/ContractId.js
src/contract/ContractNonceInfo.js
src/exports.js
test/integration/ContractFunctionParametersIntegrationTest.js
test/unit/AccountBalanceQuery.js
test/unit/ContractFunctionResultUnitTest.js
test/unit/ContractNonceInfoUnitTest.js

Support for HIP-729 - contract nonces implementation
Fixes #1644 
**Checklist**

Feature contract nonces - HIP-729 support

---

CHANGELOG.md
package.json

Release stable version
Fixes #
**Checklist**

Release 2.30.0

---

common_js_test/pnpm-lock.yaml
examples/pnpm-lock.yaml
examples/simple_rest_signature_provider/pnpm-lock.yaml
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/constants/ClientConstants.js

Update the client constants file with the new mainnet proxies
Fixes #1745 
**Checklist**

update the client constants file with the mainnet proxies

---

common_js_test/pnpm-lock.yaml
examples/pnpm-lock.yaml
examples/simple_rest_signature_provider/pnpm-lock.yaml
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/Executable.js
src/channel/WebChannel.js
src/grpc/GrpcStatus.js

Add retry logic when the SDK encounters grpc web errors
Fixes #
**Checklist**

Add retry logic on grpc web errors

---

CHANGELOG.md
package.json

Release stable version 2.33.0
Fixes #
**Checklist**

Release v2.33.0

---

src/Timestamp.js

This PR fixes an issue where given a sufficiently enough iterations of transaction id generation, there will be some occurrences of duplicate once
Fixes #1856 
**Checklist**

Ensure that generated tx ids are unique

---

CHANGELOG.md
package.json

Release stable v2.34.0
Fixes #
**Checklist**

Prepare for stable release v2.34.0

---

src/contract/ContractExecuteTransaction.js

Fixed doc comments on `setGas` and `setPayableAmount` functions.
#1887 
**Checklist**
- [ *] Documented (Code comments, README, etc.)

fixed duplicated doc comments

---

examples/consensus-pub-sub.js
src/channel/NodeMirrorChannel.js
src/topic/TopicMessageQuery.js

Add keep alive ping to the mirror node connection so we can notify on connection drops.
Fixes #1890 
**Checklist**

fix: topic subscription error handling

---

examples/consensus-pub-sub.js
examples/pnpm-lock.yaml
examples/precompile-example/ExpiryHelper.sol
examples/precompile-example/FeeHelper.sol
examples/precompile-example/HederaResponseCodes.sol
examples/precompile-example/HederaTokenService.sol
examples/precompile-example/IHederaTokenService.sol
examples/precompile-example/KeyHelper.sol
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/channel/NodeMirrorChannel.js

This PR updates the precompile system contracts used in some of the examples. The up-to-date versions are located inside the smart-contracts repo [here](https://github.com/hashgraph/hedera-smart-contracts/tree/main/contracts/hts-precompile)
Fixes #1894 
**Checklist**

Update precompile system contracts

---

.github/dependabot.yml
examples/pnpm-lock.yaml
package.json
pnpm-lock.yaml

Exclude minor and patch updates
Fixes #
**Checklist**

Ignore minor and patch updates

---

src/ObjectMap.js
src/Transfer.js
src/account/TokenNftTransferMap.js
src/account/TokenTransferAccountMap.js
src/token/AssessedCustomFee.js
src/token/TokenAssociation.js
src/token/TokenTransfer.js
src/transaction/TransactionReceipt.js
src/transaction/TransactionRecord.js
test/unit/TransactionReceipt.js
test/unit/TransactionRecord.js
test/unit/TransactionResponse.js

This PR fixes all of the badly JSON serialized fields and adds unit tests for the serialization
**Checklist**

fixed toJSON functionality in TranasctionRecord/Receipt/Response

---

CHANGELOG.md
common_js_test/pnpm-lock.yaml
examples/pnpm-lock.yaml
examples/simple_rest_signature_provider/pnpm-lock.yaml
package.json
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/token/AssessedCustomFee.js
src/transaction/TransactionRecord.js
test/unit/TransactionReceipt.js
test/unit/TransactionRecord.js
test/unit/TransactionResponse.js

Stable release `v2.35.0`
Fixes #
**Checklist**

Stable SDK release v2.35.0

---

packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/token/TokenWipeTransaction.js
test/integration/TokenWipeIntegrationTest.js

Fix the fromBytes for the tokenWipeTransaction
Fixes #1967 
**Checklist**

Fix the fromBytes for tokenWipeTransaction

---

CHANGELOG.md
package.json
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml

Stable release v2.36.0
**Checklist**

Stable release v2.36.0

---

CHANGELOG.md
package.json
packages/cryptography/package.json
packages/cryptography/pnpm-lock.yaml
packages/cryptography/src/primitive/bip32.browser.js
pnpm-lock.yaml

Beta release `v2.37.0-beta.2`
Fixes #
**Checklist**

Beta release v2.37.0-beta.2

---

CHANGELOG.md
package.json

Stable release 2.37.0
**Checklist**

Stable release 2.37.0

---

src/contract/ContractFunctionParameters.js
test/integration/ContractFunctionParametersIntegrationTest.js

- Adding an initial value of the reduce method in array methods
- Tests
Fixes #1990 
**Checklist**

Fix for "Reduce of empty array with no initial value" error in ContractFunctionParameters array methods

---

examples/account-create-with-hts.js
examples/consensus-pub-sub.js
examples/contract-nonces.js
examples/create-account-with-alias-and-receiver-signature.js
examples/create-account-with-alias.js
examples/exempt-custom-fees.js
examples/generate-txid-on-demand.js
examples/hts-nftP1-fee-create-mint-burn-associate-transfer.js
examples/hts-nftP2-kyc-upate-schedule.js
examples/hts-nftP3-pause-freeze-wipe-delete.js
examples/lazy-create-transfer-tx.js
examples/logger-functionalities.js
examples/multi-sig-offline.js
examples/nft-add-remove-allowances.js
examples/solidity-precompile-example.js
examples/time-drift.js
examples/topic-message-submit-get-all-chunks-status.js
examples/transfer-using-evm-address.js
examples/zeroTokenOperations.js
packages/cryptography/src/PrivateKey.js
src/PrivateKey.js
src/Wallet.js
src/client/Client.js
test/unit/EcdsaPrivateKey.js
test/unit/Ed25519PrivateKey.js
test/unit/TokenCreateTransaction.js
test/unit/TokenUpdateTransaction.js
test/unit/Transaction.js

Removed all warning messages.
**Checklist**

Remove all warnings

---

packages/proto/package.json
packages/proto/pnpm-lock.yaml

Update the proto package
Fixes #2039 
**Checklist**

feat: release new proto package beta version

---

CHANGELOG.md
package.json
test/unit/EcdsaPrivateKey.js
test/unit/Ed25519PrivateKey.js

Stable release v2.39.0
**Checklist**

Stable release v2.39.0

---

src/client/ManagedNetwork.js

Add a node to the selected nodes if only it hasn't been added already
Fixes #2102
**Checklist**

[#2102] Cannot read properties of undefined (reading 'accountId')

---

src/account/AccountCreateTransaction.js
src/contract/ContractCreateTransaction.js
test/unit/Transaction.js

Fixing the Hbar presentation issue after serialization/deserialization process.
Fixes #2137 
**Checklist**

fix: hbar presentation after serialization/deserialization

---

packages/proto/package.json

New beta version 2.14.0-beta.5 of proto package.
**Checklist**

release: proto beta version 2.14.0-beta.5

---

CHANGELOG.md
RELEASE.md
package.json

Preparation for SDK stable version 2.43.0.
**Checklist**

release: SDK stable version 2.43.0

---

.github/workflows/build.yml
CHANGELOG.md
package.json

Stable version 2.44.0.
**Checklist**

release: stable version 2.44.0

---

examples/update-nfts-metadata-of-non-fungible-token.js

- Removed the need to do a token association since the account we created has set max automatic associations to 10
- 
Fixes #
**Checklist**

chore: update update-nfts-metadata-of-non-fungible-token.js

---

.github/workflows/publish_release.yaml

update: release workflow

---

src/network/NetworkVersionInfo.js

Fixing a typo in SDK query file.
Fixes #2124
**Checklist**

fix: typo in SDK query file

---

examples/update-nfts-metadata-of-non-fungible-token.js
src/exports.js
src/token/TokenUpdateNftsTransaction.js
test/integration/TokenNftsUpdateTransactionIntegrationTest.js

Fixing the wrong naming convention of `TokenUpdateNftsTransaction`.
**Checklist**

fix: naming convention

---

packages/proto/package.json

Beta version v2.15.0-beta.1
**Checklist**

proto release: v2.15.0-beta.1

---

packages/proto/package.json
src/RequestType.js
src/Status.js

Beta version v2.15.0-beta.2 of proto subpackage.
**Checklist**

release: proto v2.15.0-beta.2

---

src/exports.js
src/node/NodeUpdateTransaction.js

The transaction allows to update a node from the network. Part of [HIP-869](https://hips.hedera.com/hip/hip-869).
Fixes #2336 
**Checklist**

feat: node update transaction

---

CHANGELOG.md
package.json
src/token/TokenRejectTransaction.js

Stable release v2.49.0
* fix: update taskfile status check for submodules task by @isavov in https://github.com/hashgraph/hedera-sdk-js/pull/2435
* chore: fix token permissions for deploy to github pages by @isavov in https://github.com/hashgraph/hedera-sdk-js/pull/2418
* fix: reconnect to working node by @0xivanov in https://github.com/hashgraph/hedera-sdk-js/pull/2417
* release: proto v2.15.0-beta.3 by @svetoslav-nikol0v in https://github.com/hashgraph/hedera-sdk-js/pull/2415
* update: add node id to the precheck error by @svetoslav-nikol0v in https://github.com/hashgraph/hedera-sdk-js/pull/2414
* feat: Implement TokenRejectTransaction by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2411
* update: handle PLATFORM_NOT_ACTIVE error gracefully by …

release: v2.49.0

---

CHANGELOG.md
examples/token-reject.js
package.json
src/account/AccountBalance.js

* fix: update taskfile status check for submodules task by @isavov in https://github.com/hashgraph/hedera-sdk-js/pull/2435
* chore: fix token permissions for deploy to github pages by @isavov in https://github.com/hashgraph/hedera-sdk-js/pull/2418
* fix: reconnect to working node by @0xivanov in https://github.com/hashgraph/hedera-sdk-js/pull/2417
* release: proto v2.15.0-beta.3 by @svetoslav-nikol0v in https://github.com/hashgraph/hedera-sdk-js/pull/2415
* update: add node id to the precheck error by @svetoslav-nikol0v in https://github.com/hashgraph/hedera-sdk-js/pull/2414
* feat: Implement TokenRejectTransaction by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2411
* update: handle PLATFORM_NOT_ACTIVE error gracefully by @svetoslav-nikol0v in …

release: v2.49.2

---

packages/cryptography/package.json

Bumps follow-redirects to a new version 1.15.6
**Checklist**

Beta cryptography release v1.4.8-beta.7

---

README.md

This pull request enhances the documentation on how to build the project, providing clearer and more detailed instructions.
#2408 
**Checklist**

chore(docs): Improve README build step

---

.github/workflows/build.yml
.github/workflows/common_js.yml
.github/workflows/pages.yml
.github/workflows/publish_release.yaml
.github/workflows/renovate.yml

This pull request changes the following:
- Updates the CI workflows `runs-on` labels to use the new Latitude.sh based runners.
- Closes #2494

ci: update workflows to use latitude.sh based runners

---

packages/proto/package.json

Beta proto release v2.15.0-beta.4
**Checklist**

release: proto v2.15.0-beta.4

---

packages/cryptography/package.json

Use array instead of Buffer in react native apps.

release: cryptography v1.4.8-beta.8

---

packages/cryptography/package.json

release: cryptography v1.4.8-beta.9

---

packages/cryptography/package.json

Beta cryptography release v1.4.8-beta.10

release: cryptography v1.4.8-beta.10

---

CHANGELOG.md
package.json

* fix: file append transaction id after deserialization by @SvetBorislavov in #2583

release-v2.52.0

---

CHANGELOG.md
package.json

* feat: export NodeAddressBook class by @SvetBorislavov in https://github.com/hashgraph/hedera-sdk-js/pull/2599
* feat: exports WebClient for testing grpc-web proxies by @agadzhalov in https://github.com/hashgraph/hedera-sdk-js/pull/2603
* fix: incomplete file append transaction by @SvetBorislavov in https://github.com/hashgraph/hedera-sdk-js/pull/2600

release-v2.53.0-beta.1

---

common_js_test/package.json
common_js_test/pnpm-lock.yaml
examples/react-native-example/package.json
examples/simple_rest_signature_provider/package.json
package.json
pnpm-lock.yaml

Changed some library versions, according to the recommendations from Snyk.
Related to #1645 
**Checklist**

ci: fix vulnerable library versions

---

test/integration/ContractBytecodeIntegrationTest.js
test/integration/ContractCallIntegrationTest.js
test/integration/ContractCreateFlowIntegrationTest.js
test/integration/ContractCreateIntegrationTest.js
test/integration/ContractDeleteIntegrationTest.js
test/integration/ContractExecuteIntegrationTest.js
test/integration/ContractFunctionParametersIntegrationTest.js
test/integration/ContractInfoIntegrationTest.js
test/integration/ContractUpdateIntegrationTest.js
test/integration/CryptoTransferIntergationTest.js
test/integration/FileContentsIntegrationTest.js
test/integration/FileCreateIntegrationTest.js
test/integration/FileDeleteIntegrationTest.js
test/integration/FileInfoIntegrationTest.js
test/integration/FileUpdateIntegrationTest.js
test/integration/GetCostIntegrationTest.js
test/integration/LiveHashIntegrationTest.js
test/integration/TokenBurnIntegrationTest.js
test/integration/TokenCreateIntegrationTest.js
test/integration/TokenRejectFlowIntegrationTest.js
test/integration/TokenRejectIntegrationTest.js
test/unit/MaxAttemptsOrTimeoutError.js
test/unit/NodeCreateTransaction.js
test/unit/NodeUpdateTransaction.js
test/unit/TokenRejectTransaction.js
test/unit/TransactionRecord.js

Eslint and prettier formatting due to latest typescript changes that also changed eslint version
#2663 
**Checklist**

style: code formatting

---

examples/pnpm-lock.yaml
examples/simple_rest_signature_provider/pnpm-lock.yaml

Update pnpm-lock files
**Checklist**

chore: fix pnpm-lock files

---

.github/workflows/build.yml

This PR aims to roll-back codecov upload action to an older more stable version. Once issues are resolved in latest version we can re-update.
Fixes #2683
**Checklist**

ci: Issues with codecov upload

---

package.json
packages/proto/.babelrc.json
packages/proto/package.json
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/EthereumFlow.js
src/EthereumTransaction.js
src/StakingInfo.js
src/address_book/NodeAddress.js
src/contract/ContractCreateFlow.js
src/contract/ContractFunctionParameters.js
src/contract/DelegateContractId.js
src/schedule/ScheduleId.js
src/token/TokenId.js
src/topic/TopicId.js
src/types/global.d.ts
test/integration/TokenAirdropIntegrationTest.js

- removes @types/long as it's deprecated. 
- bump long version to latest
- adds Long as global type
- 
**Checklist**

fix: typescript issue with long

---

packages/proto/package.json

Beta proto release v2.16.0-beta.3

chore(release): proto v2.16.0-beta.3

---

tck/methods/token.ts

This PR adds assessment method setter for fractional fees transactions https://github.com/hiero-ledger/hiero-sdk-tck/issues/295
#2724 
**Checklist**

chore(TCK): Added assessment method setter for TCK endpoints

---

packages/proto/package.json

Beta proto release v2.16.0-beta.4

chore(release): proto v2.16.0-beta.4

---

packages/proto/package.json

Beta proto release v2.16.0-beta.5

chore(release): proto v2.16.0-beta.5

---

packages/cryptography/package.json

Beta cryptography release v1.4.8-beta.11

chore(release): cryptography v1.4.8-beta.11

---

CHANGELOG.md
examples/Taskfile.yml
package.json

Updated the flag `--frozen-lockfile` to `--no-frozen-lockfile` in the examples Task file.

chore(release): v2.57.0-beta.3

---

.github/CODEOWNERS
.github/workflows/build.yml
.github/workflows/common_js.yml
.github/workflows/pages.yml
.github/workflows/pr_check.yml
.github/workflows/publish_release.yaml
.github/workflows/react_native.yml
.github/workflows/renovate.yml

Update the names of the self-hosted runners from hashgraph naming scheme to hiero naming scheme.
Also updating the CODEOWNERS file.
**Related Issue(s)**:
Fixes #2789

ci: update self-hosted runners for hiero-ledger

---

package.json

Beta proto release v2.16.0-beta.6

chore(release): proto v2.16.0-beta.6

---

packages/proto/package.json

- This PR updates proto package version
**Checklist**

chore: update proto package version

---

packages/proto/package.json

Beta proto release v2.16.0-beta.7

chore(release): proto v2.16.0-beta.7

---

packages/cryptography/package.json

Beta cryptography release v1.4.8-beta.13

chore(release): cryptography v1.4.8-beta.13

---

.gitignore
packages/cryptography/package.json
packages/proto/package.json

Update package.json definitions to include a publishConfig stanza for
- packages/proto
- packages/cryptography
**Related Issue(s)**:
Fixes #2816

fix(publish): Update package.json definitions to include publishConfig

---

CHANGELOG.md
package.json
packages/cryptography/package.json
packages/proto/package.json

- SDK Stable release v2.57.2
- Cryptography release  - 1.4.8-beta.14
- Proto release - 2.16.0-beta.8

chore(release): v2.57.2

---

packages/cryptography/package.json

Beta cryptography release v1.4.8-beta.15

chore(release): cryptography v1.4.8-beta.15

---

tck/server.ts

This PR changes the TCK port from `80` to `8544`
#2846 
**Checklist**

chore(fix): changed TCK port to 8544

---

packages/cryptography/package.json

Beta cryptography release: cryptography v1.5.0-beta.1

chore(release): cryptography v1.5.0-beta.1

---

packages/proto/package.json

Beta proto release v2.17.0-beta.1

chore(release): proto v2.17.0-beta.1

---

packages/cryptography/package.json

Beta cryptography release v1.5.0-beta.2

chore(release): cryptography v1.5.0-beta.2

---

package.json
pnpm-lock.yaml
rollup.config.js

We needed to fix the build config because browser aliases were not working properly.
**Checklist**

fix: build issues with browser aliases

---

.github/workflows/pr_check.yml

Update pr_check.yml file to use pull_request_target.
**Related Issue(s)**:
Fixes #2924

ci: change workflow to pull_request_target

---

packages/cryptography/test/unit/PublicKey.js

Adds unit tests for `verify` method
Fixes #
**Checklist**

test: verify message signature method

---

test/integration/AddressBookQueryTest.js

Tested against `v0.59.0` of Solo and `local node`.
Fixes https://github.com/hiero-ledger/hiero-sdk-js/issues/2912
**Checklist**

feat: Added `AddressBookQuery` test against Local node/Solo

---

.github/workflows/build.yml
.github/workflows/common_js.yml
.github/workflows/pages.yml
.github/workflows/publish_release.yaml
.github/workflows/react_native.yml

Replacing action with a version maintained by step-security
Fixes #3033 
**Checklist**

chore: replace pnpm/action-setup with step-security maintained version

---

tck/Dockerfile
tck/Taskfile.yml
tck/docker-compose.yml

This PR is renaming TCK client image from `tck-client` to `hiero-tck-client`
**Checklist**

chore: Renamed TCK client image

---

examples/create-account-with-alias.js
src/PublicKey.js
src/account/AccountCreateTransaction.js
test/integration/AccountCreateIntegrationTest.js
test/unit/AccountCreateTransaction.js
test/unit/PublicKey.js

This PR builds upon the previous enhancements to `AccountCreateTransaction`, expanding support and improving developer experience when setting keys and deriving EVM aliases.
---
- `setECDSAKeyWithAlias` and `setKeyWithAlias` now accept both `ECDSA PrivateKey` **and** `ECDSA PublicKey` inputs.
- If a `PrivateKey` is provided, the SDK will derive the alias from its corresponding public key.
- If a `PublicKey` is provided, the alias will be derived directly from that key.
This enables secure frontend-backend workflows (e.g., wallet creation flows), where only the public key is available on the backend — without requiring casting or deprecated APIs.
---
- **`setECDSAKeyWithAlias(ECDSAKey)`**  
Sets an ECDSA key (either private or public), and automatically derives and sets the corresponding …

feat: extend set key with alias to work with public ecdsa keys

---

.env.sample
README.md

Add more instructions for how to run the integration tests
Fixes #3025 
**Checklist**

fix: update README.md

---

src/Executable.js

Enabled the retry mechanism specifically for a single node when it is identified as the local node.
**Checklist**

chore(TCK): Added retry on unhealthy local node

---

tck/README.md
tck/Taskfile.yml

This PR introduces a clear and structured description of the TCK release process, along with additional task commands to streamline and support the release workflow.
**Checklist**

chore(TCK): Described and optimized release process

---

MAINTAINERS.md

Maintainers file added as described at https://lf-decentralized-trust.github.io/governance/governing-documents/MAINTAINERS-file.html

docs: create MAINTAINERS.md

---

examples/create-update-delete-node.js
packages/proto/src/proto/services/basic_types.proto
packages/proto/src/proto/services/event_core.proto
packages/proto/src/proto/services/gossip_event.proto
packages/proto/src/proto/services/node_create.proto
packages/proto/src/proto/services/node_update.proto
packages/proto/src/proto/services/response_code.proto
packages/proto/src/proto/services/state/addressbook/node.proto
packages/proto/src/proto/services/state/hints/hints_types.proto
src/Status.js
src/node/NodeCreateTransaction.js
src/node/NodeUpdateTransaction.js
test/unit/node/NodeCreateTransaction.js
test/unit/node/NodeUpdateTransaction.js

- This HIP proposes a reward mechanism that will incentivize nodes to remain active on the network. The definition of active node is described below. The minimum reward per day for nodes will be a configurable property decided by the governance of the deployed network. This minimum reward may be adjusted based on fees already paid throughout the day. It also introduces a mechanism for individual nodes to elect to enable or disable rewards.
- Also updates protobuf files to the latest tag. 
- updates Status code
- updates tests
- updates examples
- `NodeCreateTransaction declineReward`: whether the node declines rewards
- `NodeCreateTransaction setDeclineReward`: update whether the node declines reward
- `NodeUpdateTransaction declineReward`: whether the node declines …

feat: HIP 1064

---

CHANGELOG.md
Taskfile.yml
package.json
packages/proto/package.json

- Support for HIP-1064 Batch Transaction https://hips.hedera.com/hip/hip-1064 This HIP proposes a reward mechanism that will incentivize nodes to remain active on the network. [#3099](https://github.com/hiero-ledger/hiero-sdk-js/pull/3099)
- NodeCreateTransaction `declineReward`: whether the node declines rewards
- NodeCreateTransaction `setDeclineReward`: update whether the node declines reward
- Added `the x-user-agent` header to all gRPC calls to enable SDK version tracking, following the approach outlined in [#3089](https://github.com/hiero-ledger/hiero-sdk-js/pull/3089)
- Included examples that demonstrate proper error handling in realistic, real-world scenarios, including how to manage network connectivity issues when interacting with a single node. …

chore(release): v2.64.1

---

CHANGELOG.md
package.json
packages/cryptography/Taskfile.yml
packages/proto/package.json

- Support for HIP-1064 Batch Transaction https://hips.hedera.com/hip/hip-1064 This HIP proposes a reward mechanism that will incentivize nodes to remain active on the network. [#3099](https://github.com/hiero-ledger/hiero-sdk-js/pull/3099)
- NodeCreateTransaction `declineReward`: whether the node declines rewards
- NodeCreateTransaction `setDeclineReward`: update whether the node declines reward
- Added `the x-user-agent` header to all gRPC calls to enable SDK version tracking, following the approach outlined in [#3089](https://github.com/hiero-ledger/hiero-sdk-js/pull/3089)
- Included examples that demonstrate proper error handling in realistic, real-world scenarios, including how to manage network connectivity issues when interacting with a single node. …

chore(release): v2.64.2

---

CHANGELOG.md
Taskfile.yml
package.json
packages/cryptography/Taskfile.yml
packages/proto/Taskfile.yml
packages/proto/package.json

- Support for HIP-1064 Batch Transaction https://hips.hedera.com/hip/hip-1064 This HIP proposes a reward mechanism that will incentivize nodes to remain active on the network. [#3099](https://github.com/hiero-ledger/hiero-sdk-js/pull/3099)
- NodeCreateTransaction `declineReward`: whether the node declines rewards
- NodeCreateTransaction `setDeclineReward`: update whether the node declines reward
- Added `the x-user-agent` header to all gRPC calls to enable SDK version tracking, following the approach outlined in [#3089](https://github.com/hiero-ledger/hiero-sdk-js/pull/3089)
- Included examples that demonstrate proper error handling in realistic, real-world scenarios, including how to manage network connectivity issues when interacting with a single node. …

chore(release): v2.64.3

---

src/PrivateKey.js
src/Wallet.js
src/util/ASN1-Decoder.js
test/integration/LocalWalletTest.js
test/unit/PrivateKey.js
test/unit/TokenInfo.js

- adds a library that determines the keys 
- updates the files to use the correct implementation when they have to determine the key type 
Fixes #2170 
**Checklist**

feat: key algorithm identifier

---

Taskfile.yml
packages/cryptography/Taskfile.yml
packages/proto/Taskfile.yml

This PR removes updating addressbook on every build command, refactor at the Taskfiles and fixes `task update` command in the proto package.
#3109 
**Checklist**

chore(fix): Refactor release workflows

---

tck/methods/token.ts
tck/params/token.ts

This PR adds multiple airdrop cancel support to current endpoint.
**Checklist**

chore(TCK): Airdrop cancel transactionl fix

---

.github/workflows/build.yml
packages/proto/Taskfile.yml
packages/proto/src/proto/services/event_core.proto
packages/proto/src/proto/services/state/hints/hints_types.proto
packages/proto/src/proto/services/state/throttles/throttle_usage_snapshots.proto
packages/proto/src/proto/services/token_update.proto
test/integration/TokenCreateIntegrationTest.js

#3157 
Fixes: #3157
**Checklist**

test: token create with auto renew period and expiration time

---

tck/methods/file.ts
tck/params/file.ts
tck/response/file.ts

This PR implements the `FileCreateTransaction` tests documented in `test-specifications/token-service/FileCreateTransaction.md`. 
#3178 
**Checklist**

chore(TCK): Added `createFile` endpoint

---

tck/methods/file.ts

chore: fix appendFile parameters in TCK file methods

---

tck/methods/file.ts
tck/params/file.ts

This PR adds deleteFile endpoint
**Checklist**

feat(TCK): Implement DeleteFile transaction endpoint

---

src/contract/ContractInfo.js
test/integration/ContractInfoIntegrationTest.js

Add maxAutomaticTokenAssociations property and protobuf with integration test

feat: add maxAutomaticTokenAssociations property with integration test

---

src/contract/ContractDeleteTransaction.js
test/integration/ContractDeleteIntegrationTest.js
test/unit/ContractDeleteTransaction.js

- Implement permanentRemoval in Contract Delete Transaction
- Implement integration tests for permanentRemoval
- Implement unit tests for permanentRemoval
**Checklist**

feat: implement permanentRemoval

---

src/contract/ContractExecuteTransaction.js
tck/methods/contract.ts
tck/params/contract.ts
test/unit/ContractExecuteTransaction.js

- Implement TCK Contract Execute endpoint
- Add unit test for negative gas
**Checklist**

feat: add ContractExecute endpoint

---

src/account/AccountAllowanceApproveTransaction.js
src/account/TokenAllowance.js
src/account/TokenTransferMap.js
src/token/AbstractTokenTransferTransaction.js
src/token/AssessedCustomFee.js
src/token/CustomFixedFee.js
src/token/PendingAirdropRecord.js
src/token/TokenAirdropTransaction.js
src/token/TokenBurnTransaction.js
src/token/TokenCreateTransaction.js
src/token/TokenMintTransaction.js
src/token/TokenTransfer.js
src/token/TokenWipeTransaction.js
src/util.js
test/unit/AccountAllowanceApproveTransaction.js
test/unit/CustomFeeLimit.js
test/unit/TokenAllowance.js
test/unit/TokenBurnTransaction.js
test/unit/TokenMintTransaction.js
test/unit/TokenTransfer.js
test/unit/TokenWipeTransaction.js
test/unit/TransactionRecord.js
test/unit/TransferTransaction.js

Extended amount field support across the SDK to accept BigNumber and bigint types in addition to existing Long and number types, ensuring consistent handling of large amounts throughout the codebase.
**Fixes**: #1912

feat: extend amount with bigint and bn types

---

tck/methods/schedule.ts
tck/params/schedule.ts

test: New tests added for Delete of Scheduled Transactions.  issues/507

test: New tests added for Delete of Scheduled Transactions. issues/507
