hiero-ledger/hiero-sdk-js

__tests__/Hbar.test.js.ts
exports.ts
package.json
src/BaseClient.ts
src/Hbar.ts
src/TransactionBuilder.ts
src/account/AccountCreateTransaction.ts
src/account/CryptoTransferTransaction.ts
src/util.ts
yarn.lock

Also, overload all methods which take tinybar amounts to accept `Hbar`.
I'd ultimately like to deprecate the other options somehow and only except values in `Hbar` but not sure when I would wanna do that.
closes #45 

provide `Hbar` wrapper which applies tinybar conversions

---

.gitignore
__tests__/Transaction.test.ts
index-node.ts
index-web.ts
package.json
scripts/generate-flow-types.sh
src/BaseClient.ts
src/QueryBuilder.ts
src/Transaction.ts
src/TransactionBuilder.ts
yarn.lock

I'm not super happy with this solution as it currently is because it sprays `.flow` files all throughout the file structure (see below). To be fair, Typescript does this too, but Webstorm collapses the files together.

add generation of Flow typdefs

---

__tests__/account/AccountCreateTransaction.test.ts
__tests__/contract/ContractBytecodeQuery.test.ts
__tests__/contract/ContractCallQuery.test.ts
__tests__/contract/ContractCreateTransaction.test.ts
__tests__/contract/ContractDeleteTransaction.test.ts
__tests__/contract/ContractExecuteTransaction.test.ts
__tests__/contract/ContractInfoQuery.test.ts
__tests__/contract/ContractRecordsQuery.test.ts
__tests__/contract/ContractUpdateTransaction.test.ts
__tests__/file/FileAppendTransaction.test.ts
__tests__/file/FileContentsQuery.test.ts
__tests__/file/FileCreateTransaction.test.ts
__tests__/file/FileDeleteTransaction.test.ts
__tests__/file/FileInfoQuery.test.ts
__tests__/file/FileUpdateTransaction.test.ts
src/Transaction.ts
src/TransactionBuilder.ts

Signing now happens in the `TransactionBuilder` when `.build()` is called
instead of `.execute()` on `Transction`. This allows easier user of SDK.

Move automatic signing and update tests

---

__tests__/contract/CallParams.test.ts
package.json
src/contract/CallParams.ts
src/contract/ContractCallQuery.ts
src/exports.ts
yarn.lock

Implements encoding function calls in the solidity binary format. This includes encoding parameter types `uint32`, `bytes`, `string`, and `bool` which means encoding now fully supports dynamic types. 
User changes:
- `ContractCallQuery` now supports `setFunctionParameters()` being passed a `CallParams` object which
computes the the solidity binary format from js types.
Note to Reviewers: This PR is branched off another PR; PR #90 so there are a changes that look duplicated.

Implement Contract Call encoding

---

__tests__/Hbar.test.ts
__tests__/contract/ContractExecuteTransaction.test.ts
src/Hbar.ts
src/contract/ContractExecuteTransaction.ts
src/proto/ContractCall.proto

- Implement `Hbar.toString()` to print out debug information
- Add `Hbar._unit` field to store original unit the hbar converted
from.
- Update Hbar tests to use `.asTinybar()` in `toStringEquals()`
- Rename `ContractExecuteTransaction.setAmount()` to
`ContractExecuteTransaction.setPayableAmount()`

Hbar Parity

---

src/account/AccountUpdateTransaction.ts

- Implememnt `AccountUpdateTransaction.setReceiverSignatureRequired()`
- Implememnt `AccountUpdateTransaction.setProxyAccountId()`

AccountUpdateTransaction Parity

---

examples/delete-account.js
src/account/AccountDeleteTransaction.ts
src/account/AccountInfoQuery.ts
src/contract/ContractInfoQuery.ts

- Implement `AccountInfo.getCost()`
- Implement `ContractInfo.getCost()`
- Update `AccountDeleteTransaction.setDeleteAccountId()`
to automatically create a `TransactionId` with the correct
`AccountId`

AccountInfo and ContractInfo Parity

---

src/FreezeTransaction.ts

- Update `.setStartTime()`  and `.setEndTime()` to take
`hour: number` and `minute: number` parameters
instead of `date: Date`.

Fix `FreezeTransaction.set*Time()`

---

__tests__/contract/ContractFunctionParams.test.ts
examples/get-file-contents.js
src/BaseClient.ts
src/Transaction.ts
src/TransactionReceipt.ts
src/consensus/ConsensusMessageSubmitTransaction.ts
src/contract/ContractFunctionParams.ts
src/file/FileId.ts

- Fixes #183 
- Add `TransactionReceipt.consensusTopicSequenceNumber`
- Add `TransactionReceipt.consensusTopicRunningHash`
- Fixes #164 
- Deprecates `BaseClient.putNode()`
- Fixes #165 
- Deprecates `Transaction.getReceipt` and
`Transaction.getRecord()`
- Fixes #169 
- Adds support for addresses with a leading `0x` prefix.
- Fixes #171 
- Deprecates `ConsensusSubmitMessageTransaction` in favor
of a new class `ConsensusMessageSubmitTransaction`
- Fixes #182 
- Removes `.contents` in `console.log(resp.contents)`
since `FileContentsQuery` returns `Uint8Array`
#183, #164, #165, #169, #171, #182

Resolve several issues

---

src/consensus/ConsensusTopicCreateTransaction.ts
src/consensus/ConsensusTopicUpdateTransaction.ts

- Deprecate `setValidStart()` and `.setExpirationTime()` on
`ConsensusTopicCreateTransaction`.
- Rename `setAutoRenewAccount()` and `.setAutoRenewAccountId()` in
`ConsensusTopicCreateTransaction` and
`ConsensusTopicUpdateTransaction`.

Deprecate methods that shouldn't exist from `ConsensusTopic[Create|Update]Transaction`

---

__tests__/unit/der.test.ts
src/crypto/der.ts

initial support for encrypted private keys in PEMs since we have to introspect the PKCS#8 `EncryptedPrivateKeyInfo` struct (an example of which I have added to the test)

implement rudimentary DER decoding

---

CHANGELOG.md
__tests__/e2e/mirror/Consensus.test.ts
src/BaseClient.ts

- Deprecate `Client.getAccountBalance()`
- Update CHANGELOG

Implement `Client.ping()` method.

---

package.json
src/Transaction.ts
src/crypto/Ed25519PrivateKey.ts

There is already a slim decoder implementation here and there seems to be no reason for pulling in a custom base64 decoder when a two-liner with `atob`/`Buffer.from` works just as fine.
The point of `@stablelib/base64`, it seems, was to provide a decoder which delays decoding errors until the end so that it can be close to constant time on valid and invalid input of the same length. If that is needed here, this PR should be rejected (and perhaps instead the removed here code which is currently commented out should be fixed).
Refs: 87ed8eb9e72c4507a38280550753aa43bc2acd16
---
One thing that confuses me though: _what_ were those strings that `@stablelib/base64` failed to decode?
Buffer base64 decoder differs in these aspects:
1. It supports both default ([RFC3548, section …

Drop stablelib/base64 as there is already a decoder impl present here

---

examples/transfer-tokens.js

Lower initial supply
set autoRenewAccount
reduce maxTransactionFee
setTokenIds takes an array

Fixes a few issues with the token transfer example

---

src/token/TokenAssociateTransaction.js
src/token/TokenBurnTransaction.js
src/token/TokenDeleteTransaction.js
src/token/TokenFreezeTransaction.js
src/token/TokenGrantKycTransaction.js
src/token/TokenRevokeKycTransaction.js
src/token/TokenUnfreezeTransaction.js
src/token/TokenUpdateTransaction.js
src/token/TokenWipeTransaction.js

I raised issue 
https://github.com/hashgraph/hedera-sdk-js/issues/332
I think it is typo error. Maybe copy&paste.
Because All the transaction body implemented tokenCreate, so there are Transaction.fromBytes() error
Except TokenDissociateTransaction.js (It is well).

fix bug token transaction fromBytes error

---

src/Timestamp.js
src/topic/TopicMessageQuery.js
test/unit/Timestamp.js

Make sure `startTime` is one nanosecond in the future when saving the `consensusTimestamp` of a message.
Add a log statement when retrying `TopicMessageQuery`

fix: `TopicMessageQuery`

---

src/Executable.js
src/grpc/GrpcServiceError.js
src/topic/TopicMessageQuery.js
test/unit/Executable.js

Resolves: #430 
Warning: This is untested since all the nodes seem to work fine right now.

Update retry handler's to retry on gRPC error `INTERNAL` only if it matches `RST_STREAM` regex

---

examples/create-account.js
src/token/TokenCreateTransaction.js
test/integration/CustomFeesIntegrationTest.js
test/integration/TokenMintIntegrationTest.js
test/integration/TokenNftIntegrationTest.js

The following tests are failing, but I do not believe this is the result of a mistake the SDK made.
- User cannot create a token with a custom fractional fee is greater than 1
- User cannot execute the fee schedule update transaction if there is not fee schedule set already
- User cannot sign the fee schedule update transaction with any key besides the key schedule key
**Checklist**

Add `CustomFee` tests

---

examples/consensus-pub-sub.js
examples/create-account.js
examples/create-topic.js
examples/delete-account.js
examples/file-append-chunked.js
examples/get-account-balance.js
examples/get-account-balance.mjs
examples/get-account-info.js
examples/multi-sig-offline.js
examples/scheduled-transaction-multi-sig-threshold.js
examples/sign-transaction.js
examples/transfer-tokens.js

Signed-off-by: andvara-naut <dalton.kaua@launchbadge.com>
**Problem**
Right now the examples construct the client like they do in the integration tests which is way more complex than it should be. Currently it tries to use HEDERA_NETWORK environment variable, and then falls back to CONFIG_FILE, then defaults to testnet if that still fails. For examples we should simply require HEDERA_NETWORK and construct the client using Client.forName()
**Solution**
Use Client.forName() instead of the complicated mess we have right now.
This means we also should require OPERATOR_ID and OPERATOR_KEY environment variables.

Examples should construct the client more cleanly

---

CHANGELOG.md
src/query/Query.js

Free queries currently require signing even though the payment transaction is a stub with accounts and transfers being `0`. Since the original code was already checking for `operator == null` to determine if a real payment transaction was being generated I updated the parameter to be `null` whenever `this._isPaymentRequired()` is `false`.
Closes: #446 
**Checklist**

fix: free queries should not require payment transactions to be signed

---

src/account/TransferTransaction.js
test/unit/TransferTransaction.js

nft transfers do not get read in fromBytes 
Fixes: #707 
bug reproduction:
```
const tokenId = new TokenId(1,1,1);
const serialNum = 111111111;
const fromAccount = new AccountId(1,1,1);
const toAccount = new AccountId(2,2,2);
const transferTransaction = new TransferTransaction();
transferTransaction.addNftTransfer(
tokenId,
serialNum,
fromAccount,
toAccount
);
transferTransaction.setTransactionId(new TransactionId(new AccountId(1,1,1),new Timestamp(4,4)));
transferTransaction.setNodeAccountIds([new AccountId(3,3,3)]);
transferTransaction.freeze();
console.log(transferTransaction.nftTransfers);
const transferTransactionFromBytes = Transaction.fromBytes(transferTransaction.toBytes());
console.log(transferTransactionFromBytes);
```

fix: nft Transaction.fromBytes support

---

packages/cryptography/src/encoding/hex.js
src/encoding/hex.js

This removes `byteToHex` code from files where it's unused.
Only `hex.browser.js` and `hex.native.js` uses it, `hex.js` doesn't need it.
**Checklist**

chore: drop unused byteToHex

---

packages/cryptography/src/encoding/der.js
packages/cryptography/src/encoding/hex.native.js
packages/cryptography/src/primitive/slip10.js
packages/cryptography/src/util/array.js
packages/cryptography/src/util/derive.js
src/EntityIdHelper.js
src/array.js
src/channel/Channel.js
src/channel/NativeChannel.js
src/contract/ContractFunctionParameters.js
src/contract/ContractFunctionResult.js
src/util.js

This SDK both
1. Uses `Buffer.from` in some places and treats them as `Uint8Array` instances:
```
src/channel/NodeMirrorChannel.js
src/channel/NodeChannel.js
src/encoding/hex.js
src/encoding/utf8.js
packages/cryptography/src/encoding/base64.js
packages/cryptography/src/encoding/hex.js
packages/cryptography/src/encoding/utf8.js
```
Note that `Buffer.from` isn't the only source of this, as this SDK also creates pooled `Uint8Array` instances manually, e.g.: 
https://github.com/hashgraph/hedera-sdk-js/blob/9c9ace7ddb67f46f72105066d2be2fbc37991d5c/src/channel/Channel.js#L252
2. Treats `Uint8Array` instances as non-pooled in most places across the codebase (see the diff of this PR for exact locations).
This seems very fragile, as accidentally treating a pooled `Uint8Array` …

fix: use arr.buffer safely

---

package.json
src/transaction/Transaction.js
test/unit/Serialize.js

Serializing a Transaction object with  `toBytes()`  before signing it will corrupt the object in a way which will prevent any further signing. Also serializing after signing and then attempting a second signature fails for the same reason. Here I submit test cases that should all be successful and a proposed solution. Maybe there is a better fix for this.
It is not only `toBytes()` that corrupts the transaction object, it is also `getSignatures()` and `getTransactionhash()`. Which is not expected, as they are get-functions.
The use case for mixed signing and serializing is when we want to send a transaction through IPC for signing by a different process. This used to work in the 1.x verion of the Javascript SDK.
To reproduce the issue revert the commit that modifies …

fix: serialization before signing

---

packages/cryptography/src/util/derive.js

_This shouldn't change the behavior at all, just a semantic / code style fix._
Fixes https://github.com/hashgraph/hedera-sdk-js/pull/441#discussion_r760734855
`index >>> 32` is always `0xFFFFFFFF` here.
1. Shifts operate on 32-bit numbers, so the arguments are cast to 32-bit integers.
2. Only 5 bits of the shift are effective, so `>>> 32` is equivalent to  `>>> 0`.
3. The is inside an `index === 0xffffffffff` check.
This way of writing down `0xFFFFFFFF` is confusing, as that's not what one might expect for `0xFFFFFFFFFF >>> 32` to be.
```console
> 0xFFFFFFFFFF >>> 32
4294967295
> 0xFFFFFFFFFF >>> 0
4294967295
> 0xFFFFFFFF
4294967295
> 0xFF
255
```
This PR changes that to a simple hardcoded value.
We could also have used `0xffffffff` there.
Not sure why it's using …

fix: don't use `>>> 32`

---

CHANGELOG.md
src/Executable.js
src/query/CostQuery.js
test/unit/AccountInfoMocking.js
test/unit/Mocker.js

Fixes #622 
We technically did retry on `INTERNAL`, but because `RST_STREAM` regex had a `/g` flag `RST_STREAM.test(error.message)` would only pass on the first call. Any subsequent calls to `RST_STREAM.test(error.message)` would fail even if the message is identical. This is why it was not caught by our previous tests. Added a new test that uses two nodes, and returns `INTERNAL` errors multiple times from each node. I think this test can be used to cover the fact we retry on `INTERNAL` *and* switch nodes each time.
**Checklist**

fix: requests should retry on `INTERNAL` and switch nodes

---

CHANGELOG.md
package.json
packages/cryptography/src/EcdsaPrivateKey.js
packages/cryptography/src/EcdsaPublicKey.js
packages/cryptography/src/PrivateKey.js
packages/cryptography/src/primitive/ecdsa.js
packages/cryptography/src/primitive/keccak.js
packages/cryptography/test/unit/EcdsaPrivateKey.js
pnpm-lock.yaml
src/account/AccountBalance.js
src/account/LiveHashDeleteTransaction.js
src/contract/ContractExecuteTransaction.js
src/contract/ContractFunctionSelector.js
src/contract/ContractId.js
src/cryptography/keccak.js
src/token/TokenFeeScheduleUpdateTransaction.js
src/token/TokenNftInfo.js
src/transaction/NodeAccountIdSignatureMap.js
src/transaction/Transaction.js
test/integration/AccountCreateIntegrationTest.js
test/unit/AccountId.js
test/unit/EcdsaPrivateKey.js
test/unit/PublicKey.js
test/unit/keccak256.js

Fixes #844 
Took a bit to get through this rabbit hole, but ended up discovering that our `keccak256` implementation (copied from [eth-lib](https://github.com/MaiaVictor/eth-lib/blob/da0971f5b09964d9c8449975fa87933f0c9fef35/src/hash.js)) only worked on data where no byte exceeded 127. This could of been a result of us trying to add types and clean up the code, but honestly not sure. Anyways, copied the current implementation and added tests for larger bytes and also a realistic set of bytes. Also added a simple e2e test from the issue linked above.
While I was testing this though, I discovered we were checking for the wrong byte lengths in …

fix: update keccak256 implementation

---

test/integration/TokenBurnIntegrationTest.js
test/integration/TokenMintIntegrationTest.js
test/unit/TransferTransaction.js

Removes a couple of imports and formats stuff.
This PR modifies TransferTransaction, TokenMintIntegrationTest, TokenBurnIntegrationTest in order to remove unused imports and format a line for linting. It should be cosmetic besides maybe making linting less distracting.
n/a
Fixes #
**Checklist**

This is some linting related changes.

---

src/exports.js

Signed-off-by: Justin Lacy <justin@launchbadge.com>
Add Executable superclass to list of exports so Wallet Providers and Signers can implement specification defined in https://hips.hedera.com/hip/hip-338
The specification abstract classes reference Executable which is currently not included in exports.
Fixes #
**Checklist**

Add Executable superclass to exports.

---

src/ExchangeRate.js
test/unit/ExchangeRates.js

This should fix the incorrect receipt problem with Exchange.js.  
This PR modifies exchange.js' expiration time to return time in seconds (default time for getTime() is in millis, so this is divided by 1000) instead of just the seconds field. Added a unit test to demonstrate the fix.
https://github.com/hashgraph/hedera-sdk-js/issues/966
**Checklist**
- [n/a ] Documented (Code comments, README, etc.)
- [ ✓] Tested (unit, integration, etc.)

Fix for incorrect dates returned in receipts from ExchangeRate.js

---

src/contract/ContractExecuteTransaction.js

Currently interpreted protobuf amount as Hbars.
**Checklist**

Interpret ContractCall amount from proto as tinbar

---

CHANGELOG.md
src/Status.js
src/topic/TopicUpdateTransaction.js

This PR modifies `TopicUpdateTransaction` with the ability to get and set the expiration time for a given transaction. Also fixes a failing unit test for `Status` by adding a response code for `Status.SCHEDULE_PENDING_EXPIRATION` set to `314`.
Fixes #1087 
**Checklist**

Bug fix for issue #1087 - "Cannot find setExpirationTime in TopicUpdateTransaction"

---

src/transaction/TransactionResponse.js
test/integration/TransactionResponseTest.js

This PR modifies the following:
- adds `getReceiptQuery()` to `TransactionResponse`
- adds `getRecordQuery()` to `TransactionResponse`
- adds applicable integration tests to ensure the new methods return their respective queries after a transaction has been executed.
Fixes #1090 
**Checklist**

1090 Enable the SDK to retrieve a record even if a transaction failed

---

src/EthereumFlow.js
test/unit/EthereumFlowMocking.js

Signed-off-by: nikolay <n.atanasow94@gmail.com>
Fixes #
- https://github.com/hashgraph/hedera-sdk-js/issues/1181
**Checklist**

fix: EthereumFlow contract file creation

---

src/transaction/Transaction.js

fix: update several `Transaction` methods to be `private` which were marked initially as `internal`

---

CHANGELOG.md
src/contract/ContractId.js
src/contract/DelegateContractId.js

fix: undeprecate `*ContractId.fromSolidityAddress()`

---

src/contract/ContractCreateFlow.js

Fix function name according to documentation.
[Docs](https://docs.hedera.com/guides/docs/sdks/smart-contracts/create-a-smart-contract) state ContractCreateFlow inherits names from ContractCreateTransaction:
> Note: Please refer to ContractCreateTransaction()  for a complete list of applicable methods.
Function's name in ContractCreateTransaction is `setMaxAutomaticTokenAssociations`. Therefore the same name must be used in ContractCreateFlow

fix typo in function name

---

examples/react-native-example/yarn.lock

The shell-quote package before 1.7.3 for Node.js allows command injection. An attacker can inject unescaped shell metacharacters through a regex designed to support Windows drive letters. If the output of this package is passed to a real shell as a quoted argument to a command with exec(), an attacker can inject arbitrary commands. This is because the Windows drive letter regex character class is {A-z] instead of the correct {A-Za-z]. Several shell metacharacters exist in the space between capital letter Z and lower case letter a, such as the backtick character.
**CVE-2021-42740**
`9.8 / 10`
`CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H`
on shell-quote in [/react-native/yarn.lock](https://github.com/hashgraph/hedera-sdk-js/blob/-/examples/react-native-example/yarn.lock).

Patched 🐛 Improper Neutralization of Special Elements used in a Command in Shell-quote

---

CHANGELOG.md
packages/cryptography/src/PublicKey.js
packages/cryptography/test/unit/PublicKey.js

fix: `PublicKey.equals()` should use `other._key`

---

Taskfile.yml
packages/proto/Taskfile.yml

This PR adds and modifies the root's `Taskfile.yml` as well as the `packages/protos/Taskfile.yml` in order to fix the workflow and make it work flawlessly.
In summary, the whole process of preparing and setting up the SDK is simplified. Currently, it is only required to run the following command:
* **task build**
Fixes #1282 
**changes inside the** `packages/protos/Taskfile.yml`
* The task to pull and update the protos is commented out in order to update them
* Line `../../node_modules/.bin/yalc publish > /dev/null` is commented because running `task build` was failing there. I believe the issue is that the following file is created later on when running `task install` from the root `Taskfile.yml`.
The same command runs inside …

bug: fix and improve taskfiles workflow

---

src/contract/ContractFunctionParameters.js
test/unit/ContractFunctionParameters.js

Fix the offset for the Uint24 & Int24 Contract Function Params
Fixes #1294 
The offset of Uint24 & Int24 needs to be changed. It is because they are cast to Uint32 & Int32. 
**Checklist**

Fix the offset for uint24 & int24 datatypes in contract functions params

---

examples/account-create-with-hts.js

Refactor the HIP to point to testnet
-->
Fixes #1293 
Point the client to testnet.
**Checklist**

Refactor the HIP to point to testnet

---

src/PrngTransaction.js
test/unit/PrngTransaction.js

Fix the `.fromBytes()` to return the range in a transaction created from `.toBytes`
Fixes #1287
The problem was in wrong returning the range and wrong setter of the protobuf.
**Checklist**

Fix for fromBytes to return the range in PrngTransaction

---

src/topic/TopicCreateTransaction.js
src/topic/TopicMessageSubmitTransaction.js

Add getters in scope of getSomething() and marked the native getters as deprecated. The reason for that is because we want to keep consistent with the other SDKs.
Fixes #1323 & #1324 
This was discussed with Simi, and we decided to keep the SDKs consistent and to bring back the getters of scope getSomething() instead of native JS getters where they are as class params.
**Checklist**

Added getters and deprecated old ones

---

src/client/WebClient.js

Added several additional proxy URLs for mainnet, testnet and previewnet in regards to the web gRPC
Fixes #1310
After the clarification about web gRPC, we added one additional proxy URL for `mainnet` and 7 proxy URLs for each node on `testnet` and `previewnet`
**Checklist**

Added proxies for different networks

---

packages/cryptography/src/primitive/bip39.js
packages/cryptography/test/unit/bip39.js

Added NFKD normalization for mnemonic BIP39 passphrase and an unit test as well
Fixes #1334
**Checklist**

Аdded NFKD normalization for mnemonic passphrase

---

src/token/TokenNftInfo.js

Change param of getNftInfo from allowanceSpenderAccountId to spenderId as listed in protobuf.
Fixes #1332 
The change is needed because we want to be consistent with the protobuf specification
**Checklist**

Change param of getNftInfo from allowanceSpenderAccountId to spenderId

---

src/PrngTransaction.js

Signed-off-by: ochikov <ognyan@limechain.tech>
Fix for optimal param of transaction range when using PrngTransaction
Fixes #1338 
Using `?.` the sdk can be build, but it cannot be used into React. 
**Checklist**

Fix for optional param of transaction range

---

packages/cryptography/src/KeyList.js
packages/cryptography/src/primitive/bip39.js
packages/cryptography/test/unit/bip39.js
src/KeyList.js
test/integration/AccountCreateIntegrationTest.js

There was an issue when passing a single key object as a first parameter to `KeyList`, since the SDK could not proceed when getting a non-list value. Now the SDK acts properly in these cases
Fixes #1343 
Added some checks and proper handles based on parameter
**Checklist**

KeyList now handles single key properly as first parameter

---

packages/cryptography/src/PrivateKey.js
src/PrivateKey.js

Fix typo in the deprecation suggestion for `PrivateKey::generate`
Fixes #1341 
**Checklist**

Fix typo in deprecation suggestion

---

src/channel/NodeChannel.js
src/client/NodeClient.js
test/integration/AccountCreateIntegrationTest.js

Added timeout setter in NodeChannel._createUnaryClient.
Fixes #1276 
**Checklist**

Add max execution time setter for NodeChannel GRPC

---

src/Status.js

This PR adds mapping of the new status codes (`TRANSACTION_HAS_UNKNOWN_FIELDS and  ACCOUNT_IS_IMMUTABLE`) defined inside the [protobufs](https://github.com/hashgraph/hedera-protobufs/blob/ba840e5d37afd9f5b8283b862519587319bf994a/services/response_code.proto)
Fixes #1399 
**Checklist**

Add new status codes

---

src/client/Client.js
test/integration/ClientIntegrationTest.js

Signed-off-by: ochikov <ognyan@limechain.tech>
The `ping` method now throws the result of the execution of the AccountBalanceQuerry
Fixes #1412 
**Checklist**

fix ping to throw

---

package.json
packages/cryptography/package.json
packages/cryptography/src/PrivateKey.js
pnpm-lock.yaml
test/integration/TopicMessageQueryTest.js

This PR removes an unnecessary check if a transaction is frozen
Fixes #
Previously we were performing a check if a transaction is frozen and throwing an error if its not. This check is not needed as right after the check, we automatically freeze the transaction if its not
**Checklist**

Removed unnecessary check

---

examples/create-stateful-contract.js
src/query/Query.js

Fixes inaccurate cost calculation of queries. There was an issue with queries if query payment is not  explicitly set with `setQueryPayment()`, the query will fail with `INSUFFICIENT_TX_FEE`
Fixes #1425 
There was also an issue where if the `nodeAccountIds` is not empty, the check whether or not the list is locked fails because we lock it only when we set the `nodeAccountIds` which only happens if the list is empty
**Checklist**

Fix inaccurate cost calculation

---

examples/nft-add-remove-allowances.js
test/integration/NftAllowancesIntegrationTest.js

Make variables clearer
Fixes #
**Checklist**

Refactor variables

---

src/PublicKey.js
test/unit/PublicKey.js

Adds `PublicKey.fromStringECDSA()` and `PublicKey.fromStringED25519()` support
Fixes #1520 
**Checklist**

Expose some PublicKey methods

---

src/transaction/Transaction.js
test/integration/TransactionIntegrationTest.js

Fixes the override of `operator` and `operatorAccountId` in `Transaction._beforeExecute()`. This was causing the transaction to fail when using a wallet as a signer.
Fixes #1530 
**Checklist**

Fix operator and operator account id override in beforeExecute

---

.github/dependabot.yml
packages/cryptography/package.json

Change the dependabot check to monthly
Fixes #
**Checklist**

change dependabot interval to monthly

---

packages/cryptography/src/Mnemonic.js

This PR modifies the spelling of an exported constant:
* `HARDEDED` --> `HARDENED`
* N/A
* N/A
**Checklist**:

fix: spelling of `HARDENED` exported constant

---

examples/create-account-with-alias-and-receiver-signature.js
examples/create-account-with-alias.js
examples/lazy-create-transfer-tx.js
packages/cryptography/pnpm-lock.yaml
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/account/AccountCreateTransaction.js
test/integration/AccountCreateIntegrationTest.js

This PR adds the supportability to set alias when `AccountCreateTransaction` is performed
Fixes #1483 
**Checklist**

Feature add alias support in AccountCreateTX

---

package.json
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml

Added exports for types
Fixes #1559 
**Checklist**

add exports for types

---

src/transaction/List.js

An exception `list is locked` is no more thrown while trying to get the transaction hash before signing the transaction
Fixes #1410 
**Checklist**

Fix: list is locked when trying to get the hash before signing the transaction

---

src/transaction/TransactionId.js
test/unit/AccountInfoMocking.js
test/unit/TransactionId.js
test/unit/TransactionReceiptMocking.js

Fixes an issue where if the generated nanos in a `transactionId` start with `0`,  after casting the object `toString()` the `0` gets trimmed and it returns wrong `transactionId`
Fixes #1564 
**Checklist**

Add zero padding for nanos

---

packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/account/AccountAllowanceAdjustTransaction.js
src/account/AccountAllowanceApproveTransaction.js
test/integration/TokenAllowancesIntegrationTest.js

Add contractId as possible input for AccountAllowancesApproveTransaction
Fixes #1557 
**Checklist**

Add contractId as possible input for AccountAllowancesApproveTransaction

---

src/token/CustomFractionalFee.js

This PR fixes an issue where there is no impact no matter the value being set to `setAssessmentMethod()`
Fixes #1598 
**Checklist**

Add assessment method support for custom fractional fees

---

src/Executable.js

Added logging statement to show which node has been removed from the healthy nodes
Fixes #1603 
**Checklist**

Unhealthy node info

---

CHANGELOG.md
package.json

Added logger implementation with the usage of pino.js and placed some important predefined log statements inside the SDK
Fixes #1308 
**Checklist**

Add logger and transaction stats inside the SDK

---

CHANGELOG.md
package.json
src/client/ManagedNetwork.js
src/transaction/Transaction.js

Fix an issue where the SDK got stuck with `Transaction must been frozen before calculating the hash will be stable, try calling freeze` upon specific number of unhealthy nodes
Fixes #1606 
**Checklist**

Fix: unhealthy nodes

---

package.json
pnpm-lock.yaml

Fix the GRPC library to be the exact version.
Fixes #
**Checklist**

fix exact version of grpc library

---

Taskfile.yml

This PR adds `task update:addressbooks` inside `task build` so that the address book of the SDK gets updated whenever `task build` is run, which basically prepares the SDK for use
Fixes #1657 
**Checklist**

Update the addressbook on SDK build

---

src/Cache.js
src/EthereumTransactionData.js
src/EthereumTransactionDataEip2930.js
src/exports.js
test/unit/EthereumTransactionData.js

This PR adds the transaction type defined in [EIP-2930](https://eips.ethereum.org/EIPS/eip-2930) when parsing EthereumData from bytes.
Fixes #1615 
**Checklist**

Added new transaction type based on EIP-2930

---

src/account/AccountId.js
src/contract/ContractId.js
src/util.js

Add checks in `AccountId/ContractId` parsing methods `fromEvmAddress()` and `fromSolidityAddress()` in order to handle cases where users pass the wrong format of evm address in Hedera to the inappropriate method
Fixes #1742 
After this is merged, If a user passes an evm address with wrong format to one of these methods, the flow will be passed to the correct method 
**Checklist**

Add checks inside parsing methods from evm address

---

common_js_test/pnpm-lock.yaml
examples/pnpm-lock.yaml
examples/simple_rest_signature_provider/pnpm-lock.yaml
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/EntityIdHelper.js
src/account/AccountId.js
src/contract/ContractId.js

Add `populateAccountNum()` method to `AccountId/ContractId` classes that queries and gets the actual `num` field from the mirror node
Fixes #1789 
**Checklist**

Add method that queries the mirror node to get the actual num field

---

src/EntityIdHelper.js

Add error handler to `EntityId.toStringWithChecksum()`
Fixes #1803 
**Checklist**

add method handler

---

src/constants/ClientConstants.js

Node web proxies with account id's `0.0.30` and `0.0.31` are still unavailable and `0.0.7`, `0.0.9` and `0.0.11` have horrible behaviour and are yielding lots of errors
Fixes #
**Checklist**

Comment out unavailable web proxies nodes

---

src/contract/ContractFunctionParameters.js

This PR adds the possibility to pass an evm address not only as a `string` but as a `EvmAddress` object
Fixes #1816 
**Checklist**

Handle EvmAddress when passed to addAddress as a ContractFunctionParameter

---

src/client/ManagedNetwork.js
src/transaction/Transaction.js

This PR improves the node selection of the SDK
Fixes #
**Checklist**

Fix node selection improvement

---

src/account/AccountId.js

This PR fixes an issue where if you have an `AccountId` with populated `alias` field it won't yield the regular evm address when `toSolidityAddress()` is called
Fixes #1821 
**Checklist**

Enhance AccountId.toSolidityAddress() to handle alias field

---

src/account/AccountId.js

Enhanced AccountId.toSolidityAddress() so that it does not throw error if there is an alias but the key is ED25519, instead generate the long-zero format
Fixes #1821 
**Checklist**

Allow ed25519 keys to generate long-zero address from alias

---

src/account/AccountId.js

Add `populateAccountEvmAddress()` method to AccountId class that queries and gets the actual evm address field from the mirror node
Fixes #1817 
**Checklist**

Add mapi call that queries the mirror node to get the actual evm address field

---

common_js_test/pnpm-lock.yaml
examples/pnpm-lock.yaml
examples/simple_rest_signature_provider/pnpm-lock.yaml
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml
src/ExchangeRate.js
src/Transfer.js
src/token/TokenTransfer.js
src/transaction/Transaction.js
src/transaction/TransactionReceipt.js
src/transaction/TransactionRecord.js
src/transaction/TransactionResponse.js

Finalize toJson functionality in `TransactionResponse`, `TransactionReceipt` and `TransactionRecord`
Fixes #1855 
**Checklist**

Finalize toJson functionality

---

src/ExchangeRate.js
src/Transfer.js
src/token/TokenTransfer.js
src/transaction/Transaction.js
src/transaction/TransactionReceipt.js
src/transaction/TransactionRecord.js
src/transaction/TransactionResponse.js

Follow convention toJSON instead of toJson
-->
Fixes #
**Checklist**

Follow convention toJSON

---

src/channel/NodeChannel.js

Add an interval in milliseconds between pings when we make calls to consensus nodes
Fixes #1952 
**Checklist**

Add keepalive_time property when we init grpc client

---

src/client/Client.js
src/query/Query.js
test/unit/AccountInfoMocking.js
test/unit/Transaction.js

Deprecating `setMaxQueryPayment()` method in a favor of `setDefaultMaxQueryPayment()` method.
Deprecating `setMaxTransactionFee()` method in a favor of `setDefaultMaxTransactionFee()` method.
**Related issue(s)**: [#1297](https://github.com/hashgraph/hedera-sdk-js/issues/1297) 
Fixes #
**Checklist**

Add setDefaultMaxQueryPayment() and deprecate setMaxQueruPayment()

---

examples/.env.example
examples/run-all-examples.js

- Adding a .env.example file in examples directory.
- Checking if the env variable is available before running the script
Fixes #
**Checklist**

Adding new env variable

---

src/client/Client.js

This PR exposes the client operator for easier access, to enable signing arbitrary data with it.
**Checklist**

Exposing client operator with a getter

---

test/integration/TokenWipeIntegrationTest.js

Remove the `only` param.
Fixes #
**Checklist**

fix integration tests and remove .only

---

packages/cryptography/src/primitive/bip32.browser.js

Fix of `toStandardECDSAsecp256k1PrivateKey()` method in the browser
Fixes #1987
**Checklist**

Bug on mnemonic.toStandardECDSAsecp256k1PrivateKey() and mnemonic.toEcdsaPrivateKey()

---

src/constants/ClientConstants.js

This PR adds two new grpc-web endpoints to ClientConstants.js. The endpoints have been created in Cloudflare and are pointing to the correct IPs.
https://github.com/swirlds/infrastructure/issues/4299
You can e.g. `dig node28.swirldslabs.com +short` and see that the entry points to Cloudflare's DNS balancers. 
**Checklist**

Add two grpc-web endpoints for node27/28 to ClientConstants.js

---

src/PrivateKey.js
test/unit/EcdsaPrivateKey.js
test/unit/Ed25519PrivateKey.js

- deprecated `fromString()` method to prevent future confusion
- regardless of the method being deprecated, a warning message was added that suggests the developer use one of the other methods
- added a new `fromStringDer()` method that is used for a HEX-encoded string with a DER prefix for developer convenience
- tests for `fromStringDer()` method
Fixes #2027
**Checklist**

Added fromStringDer() method (and tests) and deprecated fromString() method

---

.github/workflows/publish_release.yaml

This pull request changes the following:
- Ensures playwright dependencies are installed before executing the `task publish` step.
- Writes the `.npmrc` authentication stanza as a literal without interpolation. 
- Adds the `--no-git-checks` arguments to the publish command to avoid failing to publish caused by `task build` and playwright tests.
- Closes #2061

chore(ci): ensure playwright native dependencies are installed before publishing

---

src/token/TokenUpdateTransaction.js

Added missing pauseKey prop to the method
Fixes #2094
**Checklist**

Add a Pause Key to TokenUpdateTransaction's fromProtobuf method

---

examples/mint-big-number-of-units-of-token.js
src/exports.js
src/util.js
test/integration/TokenMintIntegrationTest.js

Export Long from SDK in order to be used when it works with larger numbers.
Fixes #2106 
**Checklist**

Export Long from SDK

---

.github/workflows/publish_release.yaml

This pull request changes the following:
- Adds support for rejecting tags with an unsupported prerelease version.
- Fixes issue which prevented GitHub releases from being appropriately marked as a prerelease. 
- Adds support for appropriately applying prerelease tags to artifacts when publishing to npmjs.com
- Closes #2141

chore: ensure CI release workflow properly handles prerelease builds

---

examples/serialize-deserialize-12.js
src/account/AccountUpdateTransaction.js
src/transaction/Transaction.js
test/integration/TransactionIntegrationTest.js

Update a copy of the uncompleted transaction in the transaction list after the transaction has been frozen.
Fixes #2138 
**Checklist**

fix: update copy of transaction in transaction list

---

.github/dependabot.yml
.github/workflows/publish_release.yaml

This pull request changes the following:
* Updates the release workflow permissions to ensure the Github release can be created using the CI provided token.
* Updates `dependabot.yml` to ensure package updates are applied to both the `package.json` and `package-lock.json` files.
* Closes #2141

chore(ci): fix permissions preventing Github release creation

---

src/Executable.js
src/client/ManagedNetwork.js
src/transaction/Transaction.js

fix: use one of preselected nodes to execute the transaction

---

src/exports.js
src/system/FreezeTransaction.js
test/integration/FreezeTransactionIntegrationTest.js
test/unit/FreezeTransaction.js

- `execute()` method of `FreezeTransaction` added
- `FreezeType` exported
Fixes #2135 
**Checklist**

fix: inability to create and execute freeze transaction

---

src/client/ManagedNetwork.js

This PR removes the problematic instantiation of a logger inside a method that is invoked repeatedly.
Fixes #2194 
I couldn't run the integration tests as there were no instruction in the README. I saw errors when I ran `task test` locally: `Error: Failed to construct client for IntegrationTestEnv`
However, please let me know if anything else I should test/modify.
**Checklist**

fix: do not instantiate logger inside a method

---

src/account/TransferTransaction.js
test/unit/TransferTransaction.js

A new getter was added to the TransferTransaction class.
Fixes #2190 
**Checklist**

update: add a new getter to the TransferTransaction class

---

packages/cryptography/src/PrivateKey.js

Fixes a typo on PrivateKey.fromBytes warning
Fixes #
**Checklist**

fix: typo on PrivateKey.fromBytes warning

---

CHANGELOG.md
Taskfile.yml
examples/change-or-remove-token-keys.js
package.json

Stable release v2.47.0
**Checklist**

release: v2.47.0

---

.github/workflows/publish_release.yaml

Updates the publish_release workflow to accommodate the sdk, crypto, and proto release versions such that we can publish prerelease versions of subpackages that will not be marked as stable
Fixes #2363

ci: update publishing workflow to use appropriate pre release and stable versions

---

CHANGELOG.md
RELEASE.md
package.json

Stable release version v2.48.0
* release: proto v2.15.0-beta.2 by @svetoslav-nikol0v in https://github.com/hashgraph/hedera-sdk-js/pull/2367
* ci: update publishing workflow to use appropriate pre release and stable versions by @rbarkerSL in https://github.com/hashgraph/hedera-sdk-js/pull/2364
* feature: custom derivation paths in Mnemonic ECDSA private key derivation by @bguiz in https://github.com/hashgraph/hedera-sdk-js/pull/2341
**Checklist**

release: v2.48.0

---

.github/CODEOWNERS
.github/workflows/publish_release.yaml
packages/proto/package.json

Update the steps in publish_release.yml in order to properly evaluate conditional statements.
**Issues Fixed**
Fixes #2355

ci: 2355 sub-packages are not releasing appropriately

---

CHANGELOG.md
RELEASE.md
package.json
src/Mnemonic.js
src/Status.js
test/unit/Mnemonic.js

Stable version v2.48.1.
* release: proto v2.15.0-beta.2 by @svetoslav-nikol0v in https://github.com/hashgraph/hedera-sdk-js/pull/2367
* ci: update publishing workflow to use appropriate pre release and stable versions by @rbarkerSL in https://github.com/hashgraph/hedera-sdk-js/pull/2364
* feature: custom derivation paths in Mnemonic ECDSA private key derivation by @bguiz in https://github.com/hashgraph/hedera-sdk-js/pull/2341
**Checklist**

release: v2.48.1

---

test/integration/TokenAssociateIntegrationTest.js

Adds integration tests for `maxAutomaticTokenAssociations` according to HIP-904 test plan. 
This PR modifies `TokenAssociateIntegrationTest.js` by adding additional tests according to this test plan: 
> LIMITED AUTO ASSOCIATIONS `[0-5000]` (some sdks don’t have tests for these flows)
> 1. Given 2 fungible tokens, a sender account with a balance of the 2 fungible tokens, and a receiver account with 1 auto associations, when token1 is transferred from the sender to the receiver account, then the receiver account contains the sent balance of the token and when token2 is transferred from the sender to the receiver account, then the transaction fails with `NO_REMAINING_AUTOMATIC_ASSOCIATIONS`
> 2. Same test as above but with NFTs
> 3. Given a fungible token, a sender account …

test: add maxAutomaticTokenAssociations tests

---

packages/proto/Taskfile.yml

This PR updates the `proto:update` task to use the latest semantic version tag instead of main as a reference in the upstream protobufs repo.
Fixes #2393
**Checklist**

feat: pull protobuf changes from latest tag

---

src/exports.js
src/node/NodeDeleteTransaction.js

This is transaction allows to delete a node from the network. Part of [HIP-869](https://hips.hedera.com/hip/hip-869).
Fixes #2337 
**Checklist**

feat: node delete transaction

---

src/query/Query.js
src/transaction/TransactionReceiptQuery.js
src/transaction/TransactionRecordQuery.js

When the SDK gets `PLATFORM_NOT_ACTIVE` error, will retry to execute the transaction until reaching the max attempts limit.
Fixes #2353 
**Checklist**

update: handle PLATFORM_NOT_ACTIVE error gracefully

---

src/Executable.js
src/PrecheckStatusError.js
src/Status.js
src/contract/ContractCallQuery.js
src/query/CostQuery.js
src/query/Query.js
src/transaction/Transaction.js
src/transaction/TransactionReceiptQuery.js
src/transaction/TransactionRecordQuery.js
test/unit/AccountInfoMocking.js

Node account id which against the transaction has been executed is added to the `PrecheckStatusError`.
Fixes #2413 
**Checklist**

update: add node id to the precheck error

---

packages/proto/Taskfile.yml

This PR fixes the previously broken status check for the `"install:submodules"` task that would cause the task to always execute thus resetting any updates made to the protobufs submodule version.
Fixes #2434 
**Checklist**

fix: update taskfile status check for submodules task

---

packages/proto/Taskfile.yml

This update the condition for running the `proto:install:submodules` task to reliably determine when it should be run.
Fixes #
**Checklist**

fix: better condition for install:submodules task

---

examples/create-update-delete-node.js
src/node/NodeUpdateTransaction.js
src/node/ServiceEndpoint.js

Example that demonstrates the right way how to build a `NodeCreateTransaction`, `NodeUpdateTransaction` and `NodeDeleteTransaction` transactions and behaviour of the whole functionality.
Fixes #2407
**Checklist**

update: example for HIP-869

---

packages/cryptography/src/EcdsaPrivateKey.js
packages/cryptography/src/Ed25519PrivateKey.js
test/integration/TokenRejectIntegrationTest.js
test/unit/EcdsaPrivateKey.js
test/unit/Ed25519PrivateKey.js

**Description**: 
This PR modifies the crypto package and in particular the ECDSA and ED25519 private key classes. A user found out that a mnemonic and a key that share the same private key mismatch their public key. In order to fix it, this PR modifies the ECDSA and ED25519 so they don't add trailing zeroes. This addition only happens only when the private key is shorter than 32 bytes. Example: 3030020100300706052b8104000a04220420a5b9dedc7c7767c4a88a0ac3cc6b9171948bada579226bd550d3342db11dc800
The last 2 trailing zeroes should be added after the DER prefix  bytes (3030020100300706052b8104000a04220420) 
e.g 3030020100300706052b8104000a0422042000a5b9dedc7c7767c4a88a0ac3cc6b9171948bada579226bd550d3342db11dc8
**Fixes**
#2419
Not sure if 100 tests are enough of a …

fix: ECDSA and ED25519 public key mismatch when you get it from mnemonic

---

src/account/AccountUpdateTransaction.js

Do not reset `receiverSignatureRequired` field in `AccountUpdateTransaction` without being reset intentionally.
Fixes #2449 
**Checklist**

fix: do not reset receiverSignatureRequired in AccountUpdateTransaction by default

---

packages/cryptography/package.json

- fix: ECDSA and ED25519 public key mismatch when you get it from mnemonic
**Checklist**

release: cryptography v1.4.8-beta.6

---

CHANGELOG.md
package.json

* fix: ECDSA and ED25519 public key mismatch when you get it from mnemonic by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2451
* fix: do not reset receiverSignatureRequired in AccountUpdateTransaction by default by @svetoslav-nikol0v in https://github.com/hashgraph/hedera-sdk-js/pull/2450
* chore(deps): bump renovatebot/github-action from 40.1.12 to 40.2.5 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2447
* chore(deps): bump step-security/harden-runner from 2.8.0 to 2.9.1 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2446
* chore(deps): bump actions/setup-java from 4.2.1 to 4.2.2 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2445 
* chore(deps): bump actions/setup-node from 4.0.2 to 4.0.3 …

Beta release: v.2.50.0-beta.1

---

.github/workflows/publish_release.yaml
packages/proto/Taskfile.yml

This PR updates the submodules init command in the taskfile to respect the SHA reference to the submodule's upstream repo.
Fixes #
**Checklist**

chore: respect submodule SHA references on submodule init

---

CHANGELOG.md
package.json

Beta release v2.50.0-beta.2
* fix: ECDSA and ED25519 public key mismatch when you get it from mnemonic by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2451
* fix: do not reset receiverSignatureRequired in AccountUpdateTransaction by default by @svetoslav-nikol0v in https://github.com/hashgraph/hedera-sdk-js/pull/2450
* chore(deps): bump renovatebot/github-action from 40.1.12 to 40.2.5 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2447
* chore(deps): bump step-security/harden-runner from 2.8.0 to 2.9.1 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2446
* chore(deps): bump actions/setup-java from 4.2.1 to 4.2.2 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2445 
* chore(deps): bump …

release: v2.50.0-beta.2

---

CHANGELOG.md
package.json

Beta version v2.50.0-beta.3.
* chore(deps): bump renovatebot/github-action from 40.2.5 to 40.2.6 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2456
* feat: dynamic address book \[HIP-869\] by @svetoslav-nikol0v in https://github.com/hashgraph/hedera-sdk-js/pull/2403
**Checklist**

release: v2.50.0-beta.3

---

CHANGELOG.md
package.json

* Bump follow-redirects from 1.15.2 to 1.15.6 in /packages/cryptography by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2205/
* Bump follow-redirects from 1.15.4 to 1.15.6 in /examples by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2206
* Bump follow-redirects from 1.15.4 to 1.15.6 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2207
* Bump follow-redirects from 1.15.4 to 1.15.6 in /examples/simple_rest_signature_provider by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2208
* Bump follow-redirects from 1.15.4 to 1.15.6 in /examples/react-native-example by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2209
* feat: add dynamic address book unit tests by @ivaylonikolov7 in …

release: v2.50.0

---

tck/methods/account.ts
tck/params/account.ts

This PR implements the AccountDelete JSON-RPC method and successfully validated its functionality through comprehensive tests within the TCK project.
#2448 
**Checklist**

feat(TCK): Add AccountDelete method

---

CHANGELOG.md
package.json

Stable release v2.51.0
* feat: token airdrop transactions by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2492
* fix: react native's bip32 should use array instead of buffer due to incompatibility by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2502
* ci: update workflows to use latitude.sh based runners by @nathanklick in https://github.com/hashgraph/hedera-sdk-js/pull/2495
* chore: Added prerequisites for building the project by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2478
* chore(deps-dev): bump braces in /packages/cryptography by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2347
* chore(deps): bump braces from 3.0.2 to 3.0.3 in /common_js_test by @dependabot in …

release: v2.51.0

---

CHANGELOG.md
package.json
src/PrivateKey.js

Beta release v2.52.0-beta.1
* feat: Add multi-signature and multi-node support for signing and adding signatures by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2514
* feat: Add removeSignature/clearAllSignatures methods by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2491
* chore(deps): bump actions/setup-node from 4.0.3 to 4.0.4 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2538

release: v2.52.0-beta.1

---

.github/workflows/build.yml
.nycrc.json
Taskfile.yml
packages/cryptography/Taskfile.yml

There is an issue with the build workflow so this modifies it to use the official codecov action to try and resolve the issue.
Fixes #2557
**Checklist**

ci: Updating the build workflow to use Codecov actions instead of codecov npm package.

---

examples/serialize-deserialize-10.js
examples/serialize-deserialize-11.js
examples/serialize-deserialize-12.js
examples/serialize-deserialize-3.js
examples/serialize-deserialize-4.js
examples/serialize-deserialize-5.js
examples/serialize-deserialize-6.js
examples/serialize-deserialize-8.js
examples/serialize-deserialize-9.js
src/file/FileAppendTransaction.js
src/transaction/Transaction.js
test/integration/FileAppendIntegrationTest.js
test/integration/PrivateKey.js
test/integration/TransactionIntegrationTest.js

Implement chunk logic for toBytes method and disallow addSignature function until the next release. 
Fixes #2167 #2536
There should be refactoring done. We need to implement `ChunkTransaction`. This fix is more like a patch before the major refactor for ChunkedTransaction like the other SDKs. 
**Checklist**

fix: serialize deserialize FileAppend

---

src/transaction/TransactionReceiptQuery.js
src/transaction/TransactionResponse.js
test/integration/FileUpdateIntegrationTest.js

Updates TransactionResponse to not throw ReceiptStatus error and mark the receipt as finished
**Related issue(s)**: #2501
Fixes #2501
**Checklist**

fix: change FEE_SCHEDULE_FILE_PART_UPLOADED to not show as an error

---

CHANGELOG.md
package.json

Beta release v2.52.0-beta.2
* fix: serialize deserialize FileAppend by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2532
* fix: change FEE_SCHEDULE_FILE_PART_UPLOADED to not show as an error by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2537
* ci: Updating the build workflow to use Codecov actions instead of codecov npm package by @san-est in https://github.com/hashgraph/hedera-sdk-js/pull/2558

release: v2.52.0-beta.2

---

CHANGELOG.md
package.json

Beta release v2.52.0-beta.3
* fix: serialize deserialize FileAppend by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2532
* fix: change FEE_SCHEDULE_FILE_PART_UPLOADED to not show as an error by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2537
* ci: Updating the build workflow to use Codecov actions instead of codecov npm package by @san-est in https://github.com/hashgraph/hedera-sdk-js/pull/2558

release: v2.52.0-beta.3

---

examples/multi-node-multi-signature-removeAll.js
src/transaction/Transaction.js
test/unit/Transaction.js

This PR changes the return type of the **removeAllSignatures()** method in the **Transaction** class. Additionally, it addresses and fixes the related unit and integration tests to ensure compatibility with this change
Fixes 
#2546
**Checklist**

feat: Changed the return type of removeAllSignatures method

---

.github/codecov.yaml

Adds a codecov config file - codecov.yaml that sets test coverage threshold and target
#2574 
**Fixes**
partially #2574 
**Checklist**

ci: set codecov config

---

CHANGELOG.md
package.json

* feat: expose PendingAirdropId by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2567
* feat: Changed the return type of removeAllSignatures method by @ivaylogarnev in https://github.com/hashgraph/hedera-sdk-js/pull/2559
* fix: lock protobufjs version by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2569 
* fix: increase test timeout globally by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2566
* ci: set codecov config by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2575
* chore(deps): bump actions/checkout from 4.1.7 to 4.2.1 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2568
* chore(deps): bump micromatch in /examples/simple_rest_signature_provider by @dependabot in …

release-v2.52.0-beta.4

---

src/file/FileAppendTransaction.js
test/integration/FileAppendIntegrationTest.js
test/unit/FileAppendTransaction.js

This pull request:
- Fixes the lost transaction ID after deserialization, if previously set
- Adds chunk interval property to bring flexibility to the interval between chunks. This is helpful if a user tries to update a file that will take longer than the transaction's `validDuration`.
Fixes Partially #2167 
**Checklist**

fix: file append transaction id after deserialization

---

src/exports.js

This pull request exports the `NodeAddressBook` class.
This export is essential for enabling serializing and deserializing the `NodeAddressBook` proto.

feat: export NodeAddressBook class

---

src/file/FileAppendTransaction.js
test/integration/FileAppendIntegrationTest.js

This pull request fixes the FileAppendTransaction when building an incomplete transaction and you don't want to set contents. Previously the contents were required and you couldn't create incomplete transactions without setting the content.
**Checklist**

fix: incomplete file append transaction

---

src/exports.js

This PR exposes the WebClient in order to test grpc-web proxies easily in node.js environment

feat: exports WebClient for testing grpc-web proxies 

---

examples/get-file-contents.js

Description:
This PR adds a get-file-contents example to demonstrate how to retrieve file contents using the Hedera JavaScript SDK. This functionality is important for developers who need to access and work with file data stored on the Hedera network.
- Added get-file-contents.js example file
- Implemented file contents query using FileContentsQuery
- Included error handling and logging for better developer experience
- Demonstrated proper use of ECDSA keys or ED25519 keys with the SDK
Related issue(s):
- Fixes #2513

Get file contents

---

examples/create-account-with-thresholdkey.js

This PR introduces an example for creating an account with a threshold key in the Hedera JavaScript SDK, which mirrors the existing example in the Hedera Java SDK.
**Problem**
The Hedera Java SDK already includes an example (CreateAccountThresholdKeyExample.java) that demonstrates how to create an account with a threshold key. This feature is essential for ensuring security by requiring multiple signatures to authorize transactions.
However, there is currently no such example in the Hedera JavaScript SDK. Developers using the JavaScript SDK would greatly benefit from a similar example to guide them through creating accounts with threshold keys in JavaScript, as it's a crucial security feature.
**Solution**
This PR provides a new example in the JavaScript SDK that follows …

Create account with threshold key 

---

tck/methods/token.ts
tck/params/token.ts
tck/response/token.ts
tck/utils/constants/properties.ts

Description:
This PR implements the TokenCreate JSON-RPC method and successfully validated its functionality through comprehensive tests within the TCK project.
Related issue(s):
#2584 
**Checklist**

feat(TCK): Add TokenCreate method

---

src/token/TokenUpdateNftsTransaction.js
test/unit/TokenUpdateNftsTransaction.js

This PR fixes `_fromProtobuf` inside of `TokenUpdateNftsTransaction` to use the correct `tokenUpdateNfts` field instead of `tokenUpdate`. Upon investigating https://github.com/hashgraph/hedera-wallet-connect/issues/265, we realized this property was not being referenced properly. 
Fixes https://github.com/hashgraph/hedera-wallet-connect/issues/265
You can confirm the error happens outside of this branch by running the following code: 
```
import Long from "long";
import { TokenUpdateNftsTransaction, Transaction } from "./exports.js";
const updateNftsTransaction = new TokenUpdateNftsTransaction()
.setTokenId("0.0.123")
.setSerialNumbers([Long.fromInt(1)])
.setMetadata(new TextEncoder().encode("metadata"));
const parsedTx = …
```

fix: incorrect protobuf body field used

---

src/token/AbstractTokenTransferTransaction.js

This PR introduces a getter to expose the `tokenTransfers` property of `AbstractTokenTransferTransaction`, making it accessible for use.
#2615 
**Checklist**

feat: tokenTransfer property exposed in AbstractTokenTransferTransaction

---

CHANGELOG.md
package.json
test/unit/TokenUpdateNftsTransaction.js
test/unit/TopicMessageMocking.js

* feat: Refactor SignatureMap for Multi-Transaction Support in _signedTransactions by @ivaylonikolov7 and @SvetBorislavov in https://github.com/hashgraph/hedera-sdk-js/pull/2601
* feat: tokenTransfer property exposed in AbstractTokenTransferTransaction by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2616
* feat: example for get file contents by @b-l-u-e in https://github.com/hashgraph/hedera-sdk-js/pull/2578
* feat: example for create account with threshold key @b-l-u-e in https://github.com/hashgraph/hedera-sdk-js/pull/2579
* fix: TopicMessageQuery#unsubscribe() attempts to re-subscribe by @Jexsie in https://github.com/hashgraph/hedera-sdk-js/pull/2582
* fix: incorrect protobuf body field used by @kantorcodes in …

release: v2.53.0-beta.2

---

src/constants/ClientConstants.js

This PR adds accounts 32, 33, and 34 to the `ClientConstants.js` library
[infrastructure/issues/6377](https://github.com/swirlds/infrastructure/issues/6377)
Each of the URLs provided here is available via `dig` and `nslookup`
**Checklist**

chore: adding account 32, 33, and 34 endpoints to the clientconstants.js

---

examples/multi-node-multi-signature-remove.js
examples/multi-node-multi-signature-removeAll.js
examples/multi-node-multi-signature.js
examples/multi-sig-offline.js

Comment out all non-working examples
https://github.com/hashgraph/hedera-sdk-js/issues/2619
**Checklist**

fix: comment out not-working examples

---

CHANGELOG.md
package.json

Beta release v2.53.0-beta.3
* fix: comment-out-not-working-examples by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2620
* feat: adding account 32, 33, and 34 endpoints to the clientconstants.js by @rustyShacklefurd in https://github.com/hashgraph/hedera-sdk-js/pull/2607
* feat: Refactor SignatureMap for Multi-Transaction Support in _signedTransactions by @ivaylonikolov7 and @SvetBorislavov in https://github.com/hashgraph/hedera-sdk-js/pull/2601
* feat: tokenTransfer property exposed in AbstractTokenTransferTransaction by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2616
* feat: example for get file contents by @b-l-u-e in https://github.com/hashgraph/hedera-sdk-js/pull/2578
* feat: example for create account with threshold key @b-l-u-e …

release: v2.53.0-beta.3

---

CHANGELOG.md
package.json

Beta release v2.53.0-beta.4
* fix: comment-out-not-working-examples by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2620
* feat: adding account 32, 33, and 34 endpoints to the clientconstants.js by @rustyShacklefurd in https://github.com/hashgraph/hedera-sdk-js/pull/2607
* feat: Refactor SignatureMap for Multi-Transaction Support in _signedTransactions by @ivaylonikolov7 and @SvetBorislavov in https://github.com/hashgraph/hedera-sdk-js/pull/2601
* feat: tokenTransfer property exposed in AbstractTokenTransferTransaction by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2616
* feat: example for get file contents by @b-l-u-e in https://github.com/hashgraph/hedera-sdk-js/pull/2578
* feat: example for create account with threshold key @b-l-u-e …

release: v2.53.0-beta.4

---

CHANGELOG.md
package.json

Stable release v2.53.0
* feat: Refactor SignatureMap for Multi-Transaction Support in _signedTransactions by @ivaylonikolov7 and @SvetBorislavov in https://github.com/hashgraph/hedera-sdk-js/pull/2601
* feat: export NodeAddressBook class by @SvetBorislavov in https://github.com/hashgraph/hedera-sdk-js/pull/2599
* feat: exports WebClient for testing grpc-web proxies by @agadzhalov in https://github.com/hashgraph/hedera-sdk-js/pull/2603
* feat: adding account 32, 33, and 34 endpoints to the clientconstants.js by @rustyShacklefurd in https://github.com/hashgraph/hedera-sdk-js/pull/2607
* feat: tokenTransfer property exposed in AbstractTokenTransferTransaction by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2616
* feat: example for get file contents by @b-l-u-e …

release: v2.53.0

---

examples/initialize-client-with-mirror-node-adress-book.js
src/client/NodeClient.js
src/network/AddressBookQuery.js
test/unit/NodeClient.js

This PR adds a new method to the NodeClient class, allowing it to be initialized with only a MirrorNetwork address. After setting the MirrorNetwork, an AddressBookQuery is executed to retrieve the full consensus node network, which is then configured in the client. An example usage is also provided for clarity.
#2632 
**Checklist**

feat: Add method to `NodeClient` for Initialization with `MirrorNetwork` only

---

test/unit/FileAppendTransaction.js

Adds more unit tests for FileAppend coverage. Last PR that improves FileAppend didn't include unit tests which lowered the code coverage. This PR fixes this by adding the necessary unit tests.
Related Issues:
#2588 
**Checklist**

test: add FileAppend unit tests for better code coverage

---

src/account/AccountUpdateTransaction.js
src/contract/ContractFunctionResult.js
src/contract/ContractUpdateTransaction.js
src/file/FileUpdateTransaction.js
src/node/NodeUpdateTransaction.js
src/token/TokenTransfer.js
src/token/TokenUpdateNftsTransaction.js
src/token/TokenUpdateTransaction.js
src/topic/TopicUpdateTransaction.js
test/unit/AccountUpdateTransaction.js
test/unit/ContractUpdateTransaction.js
test/unit/FileUpdateTransaction.js
test/unit/NodeUpdateTransaction.js
test/unit/TokenTransfer.js
test/unit/TokenUpdateNftsTransaction.js
test/unit/TokenUpdateTransaction.js
test/unit/TopicUpdateTransaction.js

This pull request updates the `_fromProtobuf` function of the following classes:
- AccountUpdateTransaction
- ContractFunctionResult
- ContractUpdateTransaction
- FileUpdateTransaction
- NodeUpdateTransaction
- TokenTransfer
- TokenUpdateNftsTransaction
- TokenUpdateTransaction
- TopicUpdateTransaction
This change is required because the protobufs for the bodies (or the data) of these classes use the [primitive wrappers](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/wrappers.proto)
These wrappers are necessary when the property is nullable. Since the wrapper is a sub-message with a `value` it assumed that:
- if the sub-message is null, the value is null
- if the sub-message does not contain the value property, the value is null
- if the …

fix: _fromProtobuf functions where google primitive wrappers used

---

CHANGELOG.md
package.json

Stable release v2.54.1
* feat: Add node AccountId to timeout/max attempt errors by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2631
* feat: Add method to NodeClient for Initialization with MirrorNetwork only by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2635
* fix: \_fromProtobuf functions where google primitive wrappers used (#2657) by @SvetBorislavov in https://github.com/hashgraph/hedera-sdk-js/pull/2657
* fix: update typescript version by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2666
* chore(deps-dev): bump vite from 4.4.9 to 4.5.3 in /packages/cryptography by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2237
* chore(deps-dev): bump fast-xml-parser from 4.2.7 to 4.4.1 in …

release: v2.54.1 

---

CHANGELOG.md
package.json

Stable 2.54.2
* feat: Add node AccountId to timeout/max attempt errors by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2631
* feat: Add method to NodeClient for Initialization with MirrorNetwork only by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2635
* fix: \_fromProtobuf functions where google primitive wrappers used (#2657) by @SvetBorislavov in https://github.com/hashgraph/hedera-sdk-js/pull/2657
* fix: update typescript version by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2666
* chore(deps-dev): bump vite from 4.4.9 to 4.5.3 in /packages/cryptography by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2237
* chore(deps-dev): bump fast-xml-parser from 4.2.7 to 4.4.1 in …

release: v2.54.2

---

examples/create-account-with-thresholdkey.js
examples/multi-node-multi-signature-remove.js
examples/multi-node-multi-signature-removeAll.js
examples/multi-node-multi-signature.js
examples/multi-sig-offline.js
examples/token-reject.js

Uncomments non-working example after the latest changes and applies necessary changes for them to work again.
Fixes #2619
Notes for reviewer: 
Removed the last steps in the example(where we add the signatures) because after the latest sig map changes adding back the signatures after using `removeSignature` functionalities create unnecessary code gymnastics.  
**Checklist**

fix: rework examples

---

.github/workflows/build.yml
.github/workflows/common_js.yml
.github/workflows/pages.yml
.github/workflows/publish_release.yaml
.github/workflows/react_native.yml

pnpm/action-setup has to be replaced with a variant maintained by step-security in all workflows utilizing the action.
Fixes #2675 
N/A
**Checklist**

chore: replace pnpm/action-setup with a step-security maintained one

---

packages/proto/Taskfile.yml
packages/proto/src/proto/services/basic_types.proto
packages/proto/src/proto/services/event_consensus_data.proto
packages/proto/src/proto/services/event_core.proto
packages/proto/src/proto/services/event_descriptor.proto
packages/proto/src/proto/services/event_transaction.proto
packages/proto/src/proto/services/gossip_event.proto
packages/proto/src/proto/services/response_code.proto
packages/proto/src/proto/services/state_signature_transaction.proto
packages/proto/src/proto/services/transaction_body.proto
src/RequestType.js
src/Status.js
test/unit/Mocker.js

This PR updates protobuf files to align with the latest Hedera platform specifications. The Taskfile has been refactored to move the protos from `platform` directory to the `services` protos directory. Test failures caused by these changes have been resolved.
**Checklist**

fix: Protobufs updated

---

packages/proto/src/proto/services/response_code.proto
src/FeeComponents.js
src/Status.js
src/types/long.d.ts

Adds `types/long.d.ts` due to the transpiler not being able to find the default `Long` type. We already use `allowSyntheticDefaultImports` property but if I try to import only the type of `long` using `typedef {import("long")}` it will transpile the code to `typedef {import("long")}.default` inside the `.d.ts` files in the SDK. This will show an error. I try to circumvent this error by importing the `Long` class declaration locally. I think it might have something to do with the way they export the Long class. Similar issues has been raised [here](https://github.com/dcodeIO/long.js/issues/118) and [here](https://github.com/dcodeIO/long.js/issues/109).
**Checklist**

fix: add long types declaration locally so we dont have to rely on remote declaration

---

packages/proto/package.json

Beta @hashgraph/proto release v2.16.0-beta.2
The logic for generating proto files has been revised, and the files have been updated in the corresponding directory. A new sub-repo has been introduced, pointing to the services repository, where the proto files are now maintained. The entire repository is pulled into the JavaScript SDK, and only the necessary proto files are moved into the proto/src/proto folder, while the sdk and mirror directories remain hardcoded.

chore(release): proto v2.16.0-beta.2

---

CHANGELOG.md
package.json

Stable release v2.55.0
What's Changed
* feat: Added InvalidNode check in the Executable by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2661
* fix: Protobufs updated by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2691
* fix: typescript issue with long by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2692
* ci: add pr title check workflow to ensure conventional commits by @PavelSBorisov in https://github.com/hashgraph/hedera-sdk-js/pull/2661

chore(release): v2.55.0

---

src/node/NodeUpdateTransaction.js

This pull request updates the _makeTransactionData of NodeUpdateTransaction to reduce the size of the buffer when no bytes are set for the `_grpcCertificateHash` and `_gossipCaCertificate`

feat: update _makeTransactionData of NodeUpdateTransaction

---

common_js_test/src/test.js

Check if at least one node managed to execute transaction.
**Checklist**

fix: check for successful node execution

---

CHANGELOG.md
package.json
src/channel/NodeChannel.js

* feat: Custom web proxies usage and documentation @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2729
* feat: bump node version by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2647
* feat: HIP 423 Long Term Scheduled Transactions by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2708
* feat: Enhance gRPC TLS by Dynamic Certificate Retrieval by @ivaylogarnev-limechain in https://github.com/hashgraph/hedera-sdk-js/pull/2718
* fix: check for successful node execution by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2730
* chore(deps-dev): bump rollup in /packages/cryptography by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2544
* chore(deps): bump nanoid in …

chore(release): v2.56.0

---

CHANGELOG.md
examples/pnpm-lock.yaml
package.json
src/query/MirrorNodeContractCallQuery.js
src/query/MirrorNodeContractEstimateQuery.js
tck/methods/token.ts

* feat: Implement MirrorNodeContractQuery by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2723
* feat: Add configurable commit hash for JS builds. by @ggstyokov in https://github.com/hashgraph/hedera-sdk-js/pull/2751
* feat: add new nextExchangeRate property to receipt by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2727
* docs: add configuration.md file by @ivaylonikolov7 in https://github.com/hashgraph/hedera-sdk-js/pull/2687
* chore(deps): bump ncipollo/release-action from 1.14.0 to 1.15.0 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2760
* chore(deps): bump step-security/harden-runner from 2.10.2 to 2.10.3 by @dependabot in https://github.com/hashgraph/hedera-sdk-js/pull/2758
* chore: delete AccountStakersQuery  by …

chore(release): v2.57.0-beta.1

---

examples/Taskfile.yml
examples/package.json
examples/pnpm-lock.yaml
package.json

This PR downgrades the `pnpm lock file` version for the examples and locks the `dpdm` version to ensure compatibility and stability across environments. These changes aim to resolve version-related issues and improve consistency in dependencies.

chore(release): v2.57.0-beta.4

---

CHANGELOG.md
package.json
src/contract/ContractInfoQuery.js
src/transaction/Transaction.js

Stable release v2.57.0
* test: fix TopicMessage related tests by @ivaylonikolov7 in https://github.com/hiero-ledger/hiero-sdk-js/pull/2799
* docs: documentation batch for classes by @ivaylonikolov7 in https://github.com/hiero-ledger/hiero-sdk-js/pull/2771
* docs: update chunk size comments by @SimiHunjan in https://github.com/hiero-ledger/hiero-sdk-js/pull/2738
* chore(deps): bumped Typescript version by @ivaylogarnev-limechain in https://github.com/hiero-ledger/hiero-sdk-js/pull/2797
* chore(deps): bump renovatebot/github-action from 41.0.8 to 41.0.10 by @dependabot in https://github.com/hiero-ledger/hiero-sdk-js/pull/2805
* chore(deps): bump typedoc by @ivaylonikolov in https://github.com/hiero-ledger/hiero-sdk-js/pull/2800
* docs: update token-airdrop-example.js by @michielmulders in …

chore(release): v2.57.0

---

CHANGELOG.md
package.json

Stable release v2.57.1
* test: fix TopicMessage related tests by @ivaylonikolov7 in https://github.com/hiero-ledger/hiero-sdk-js/pull/2799
* docs: documentation batch for classes by @ivaylonikolov7 in https://github.com/hiero-ledger/hiero-sdk-js/pull/2771
* docs: update chunk size comments by @SimiHunjan in https://github.com/hiero-ledger/hiero-sdk-js/pull/2738
* docs: update token-airdrop-example.js by @michielmulders in https://github.com/hiero-ledger/hiero-sdk-js/pull/2593
* chore(deps): bumped Typescript version by @ivaylogarnev-limechain in https://github.com/hiero-ledger/hiero-sdk-js/pull/2797
* chore(deps): bump renovatebot/github-action from 41.0.8 to 41.0.10 by @dependabot in https://github.com/hiero-ledger/hiero-sdk-js/pull/2805
* chore(deps): bump typedoc by @ivaylonikolov in …

chore(release): v2.57.1

---

.github/workflows/build.yml
Taskfile.yml
src/Executable.js
src/query/Query.js
test/integration/ContractFunctionParametersIntegrationTest.js
test/unit/EcdsaPrivateKey.js
test/unit/Ed25519PrivateKey.js

- Parallel testing in miltiple threads to increase test execution speed.  
- Use `MirrorNodeContractCallQuery` where applicable to circumvent throttle mechanic
- reduce stress iteration count to improve unit test speed
- remove backoff mechanism when running on local-node
- increase retry attempts when running on local node
**Fixes** #2710 
**Checklist**

feat: parallel testing

---

package.json
packages/cryptography/package.json
packages/cryptography/pnpm-lock.yaml
packages/proto/package.json
packages/proto/pnpm-lock.yaml
pnpm-lock.yaml

Description:
This PR fixes issue with failing task install script due to types/node version incompatibility for pnpm versions greater than or equal to 9.
Related issue(s):
https://github.com/hiero-ledger/hiero-sdk-js/issues/2828
Checklist

chore(fix): resolve incompatibility with latest pnpm

---

examples/create-contract-with-value.js

This PR fixes create-contract-with-value example by executing the correct transaction. It was executing `ContractCreateTransaction` 2nd time therefore throwing `DUPLICATE_TRANSACTION`
#2801 
**Checklist**

fix: create-contract-with-value example

---

CHANGELOG.md
package.json

* feat: account create transaction with key derived alias by @venilinvasilev in https://github.com/hiero-ledger/hiero-sdk-js/pull/2834
* feat: parallel testing by @ivaylonikolov7 in https://github.com/hiero-ledger/hiero-sdk-js/pull/2821
* feat: fix examples and run them in every new PR/per push by @ivaylonikolov7 in https://github.com/hiero-ledger/hiero-sdk-js/pull/2830
* fix: Hitting unhealthy node 10 times by @ivaylogarnev-limechain in https://github.com/hiero-ledger/hiero-sdk-js/pull/2819
* fix: resolve incompatibility with latest pnpm by @venilinvasilev in https://github.com/hiero-ledger/hiero-sdk-js/pull/2829
* fix: create-contract-with-value example by @venilinvasilev in https://github.com/hiero-ledger/hiero-sdk-js/pull/2825
* test: add topic info tests by @ivaylonikolov7 in …

chore(release): v2.58.0

---

package.json
pnpm-lock.yaml
test/unit/NodeClient.js

Bump grpc-js package
#2835 
We had an issue with SSL connection that was blocking the bump of grpc-js. That was resolved recently via #2718  
**Checklist**

chore: bump grpc-js

---

.gitmodules

Description:
This PR changes Protobufs submodule path to the new location of the repository - [Hiero](https://github.com/hiero-ledger/hiero-consensus-node/)
Related issue(s):
#2871  
Checklist

fix: Changed Protobufs submodule path

---

README.md
examples/react-native-example/App.tsx
examples/react-native-example/package.json
examples/react-native-example/yarn.lock
package.json
pnpm-lock.yaml

This PR introduces official support for Expo SDK v51 and above in @hashgraph/sdk. These updates ensure full compatibility by addressing necessary dependencies and removing outdated configurations.
Removed expo dependency, as it is no longer required.
Added react-native-get-random-values polyfill to support crypto.getRandomValues with secure native random value generation.
Implemented a polyfill for process.nextTick to maintain compatibility across environments.
Enforced Expo SDK version constraint for v51 and above to align with the latest updates.
Resolves [#2886](https://github.com/hiero-ledger/hiero-sdk-js/issues/2886)

feat: add expo sdk  v51+ support

---

src/Wallet.js
src/account/AccountAllowanceAdjustTransaction.js
src/account/AccountAllowanceApproveTransaction.js
src/account/AccountId.js
src/contract/ContractId.js

This change ensures handling of different shard and realm configurations in places where it was hardcoded as `0`
Fixes: #2880

fix: zero assumed shard and realm

---

packages/cryptography/src/EcdsaPrivateKey.js
test/integration/PrivateKey.js
test/unit/PrivateKey.js

An error with the leading zeroes was raised by our community. Solved it by fixing `ECDSAPrivateKey.toBytesRaw` function. It was appending the zeroes instead of prepending them when the key was too short.
**Checklist**

fix: ECDSA private key

---

CHANGELOG.md
package.json
packages/cryptography/package.json

Stable release **v2.60.0**
* fix: ECDSA private key by @ivaylonikolov7 in https://github.com/hiero-ledger/hiero-sdk-js/pull/2903
* chore(deps-dev): bump chromedriver from 132.0.0 to 133.0.3 in /packages/cryptography by @dependabot in https://github.com/hiero-ledger/hiero-sdk-js/pull/2910
* chore(deps): bump pino-pretty from 10.3.1 to 13.0.0 by @dependabot in https://github.com/hiero-ledger/hiero-sdk-js/pull/2907
* chore(deps-dev): bump chromedriver from 132.0.0 to 133.0.3 by @dependabot in https://github.com/hiero-ledger/hiero-sdk-js/pull/2906
* chore(deps-dev): bump mocha from 10.8.2 to 11.1.0 by @dependabot in https://github.com/hiero-ledger/hiero-sdk-js/pull/2909
* chore(deps-dev): bump eslint-plugin-compat from 4.2.0 to 6.0.2 by @dependabot in …

chore(release): v2.60.0

---

.github/CODEOWNERS

Description:
As defined in Hiero (https://github.com/hiero-ledger/governance?tab=readme-ov-file#definitions-of-roles) all committers should have write access which includes acting as a code owner for the repo.
Closes #2862

chore: fix committers group access

---

test/integration/AccountBalanceIntegrationTest.js
test/integration/AccountCreateIntegrationTest.js
test/integration/AccountDeleteIntegrationTest.js
test/integration/AccountInfoIntegrationTest.js
test/integration/AccountRecordsIntegrationTest.js
test/integration/AccountUpdateIntegrationTest.js
test/integration/ClientIntegrationTest.js
test/integration/CryptoTransferIntergationTest.js
test/integration/CustomFeesIntegrationTest.js
test/integration/LiveHashIntegrationTest.js
test/integration/MirrorNodeContractQuery.js
test/integration/NftAllowancesIntegrationTest.js
test/integration/PrivateKey.js
test/integration/ScheduleCreateIntegrationTest.js
test/integration/TokenAirdropIntegrationTest.js
test/integration/TokenAllowancesIntegrationTest.js
test/integration/TokenAssociateIntegrationTest.js
test/integration/TokenBurnIntegrationTest.js
test/integration/TokenCancelAirdropTransaction.js
test/integration/TokenClaimAirdropTransaction.js
test/integration/TokenDeleteIntegrationTest.js
test/integration/TokenDissociateIntegrationTest.js
test/integration/TokenFreezeIntegrationTest.js
test/integration/TopicCreateIntegrationTest.js
test/integration/utils/Fixtures.js

This refactors parts of the integration tests to use fixtures.
Adds new fixtures to be used in other tests.
Changes the way transaction state is handled in fixtures, so it is consistent as in usage.
https://github.com/hiero-ledger/hiero-sdk-js/issues/2872

refactor: used fixtures in tests

---

src/channel/NodeChannel.js

This PR modifies the `gRPC` library settings and activates the retry feature within the channel, allowing it to attempt reconnection in case of a failure.
#2926 
**Checklist**

fix: Enabled gRPC retry mechanism

---

CHANGELOG.md
package.json
packages/cryptography/package.json
src/channel/NodeChannel.js

* feat: Verify the SDK can use .setMirrorNetwork() with Solo by @ivaylogarnev-limechain in https://github.com/hiero-ledger/hiero-sdk-js/pull/2933
* fix: Enabled gRPC retry mechanism by @ivaylogarnev-limechain in https://github.com/hiero-ledger/hiero-sdk-js/pull/2940
* fix: Hashgraph/cryptography within browser tests by @ivaylogarnev-limechain in https://github.com/hiero-ledger/hiero-sdk-js/pull/2927
* ci: refactor: used fixtures in tests by @venilinvasilev in https://github.com/hiero-ledger/hiero-sdk-js/pull/2914
* ci: change workflow to pull_request_target by @andrewb1269hg in https://github.com/hiero-ledger/hiero-sdk-js/pull/2925
* chore: remove node08,node13,node23 from mainnet constants by @kfbr in https://github.com/hiero-ledger/hiero-sdk-js/pull/2913
* chore(deps-dev): bump c8 from …

chore(release): v2.61.0-beta.1

---

CHANGELOG.md
examples/package.json
package.json

* feat: Verify the SDK can use .setMirrorNetwork() with Solo by @ivaylogarnev-limechain in https://github.com/hiero-ledger/hiero-sdk-js/pull/2933
* fix: Enabled gRPC retry mechanism by @ivaylogarnev-limechain in https://github.com/hiero-ledger/hiero-sdk-js/pull/2940
* fix: Hashgraph/cryptography within browser tests by @ivaylogarnev-limechain in https://github.com/hiero-ledger/hiero-sdk-js/pull/2927
* ci: refactor: used fixtures in tests by @venilinvasilev in https://github.com/hiero-ledger/hiero-sdk-js/pull/2914
* ci: change workflow to pull_request_target by @andrewb1269hg in https://github.com/hiero-ledger/hiero-sdk-js/pull/2925
* chore: remove node08,node13,node23 from mainnet constants by @kfbr in https://github.com/hiero-ledger/hiero-sdk-js/pull/2913
* chore(deps-dev): bump c8 from …

chore(release): v2.61.0-beta.2

---

examples/schedule-network-update.js
src/client/Client.js
src/client/WebClient.js

This gives the possibility of the sdk client to update the address book manually and adds an example of usage.
Current flow of the client network update:
**Client initialization ->>> (Optional) Manual network update → Wait → Scheduled network update → Wait → Repeat...**
We chose this approach to allow users to update the network manually, because initiating the address book update during client initialization would introduce a breaking change to users. Since the update process is asynchronous, it would require awaiting the operation.
Related issues:
https://github.com/hiero-ledger/hiero-sdk-js/issues/2918

feat: manual update client address book

---

README.md

Users weren't aware they need to build the project and then install the dependencies before running the example.
Fixes #
https://github.com/hiero-ledger/hiero-sdk-js/issues/2535
**Checklist**

docs: add note in documentation when running examples 

---

CHANGELOG.md
package.json

Stable release v2.61.0
-   fix: disable auto renew assignment on topic and token create by @SimiHunjan in @dependabot in https://github.com/hiero-ledger/hiero-sdk-js/pull/2945
-   feat: manual update client address book by @venilinvasilev in https://github.com/hiero-ledger/hiero-sdk-js/pull/2928
-   docs: add some comments about the toSolidityAddress function by @Neurone in https://github.com/hiero-ledger/hiero-sdk-js/pull/2220
-   docs: add note in documentation when running examples by @ivaylonikolov7 in https://github.com/hiero-ledger/hiero-sdk-js/pull/2962
-   chore(deps): bump @babel/runtime in /examples/react-native-example by @dependabot in 
https://github.com/hiero-ledger/hiero-sdk-js/pull/2947
-   chore(deps): bump @babel/helpers in /examples/react-native-example by @dependabot …

chore(release): v2.61.0

---

Taskfile.yml

Reopenned https://github.com/hiero-ledger/hiero-sdk-js/pull/2388 because of some conflict in the old PR where the old nodes refused to rerun.
**Checklist**

chore: break down task into build:prep and build:actual

---

examples/package.json
examples/pnpm-lock.yaml
package.json
pnpm-lock.yaml

This bumps the packages that use the outdated elliptic version to the latest.

chore: bump elliptic peer depеndency

---

.github/workflows/build.yml
src/token/TokenCreateTransaction.js
test/integration/ContractFunctionParametersIntegrationTest.js
test/integration/TokenAssociateIntegrationTest.js
test/integration/TokenUpdateIntegrationTest.js
test/integration/WalletIntegrationTest.js
test/integration/client/BaseIntegrationTestEnv.js

This update resolves an issue in the integration tests where the dedicated test account could run out of Hbar, leading to INSUFFICIENT_PAYER_BALANCE errors when running large test suites. Going forward, the tests will use one of the auto-generated accounts provided by the local node, ensuring sufficient balance and more stable test execution across all suites.
https://github.com/hiero-ledger/hiero-sdk-js/issues/2964
Fixes #
https://github.com/hiero-ledger/hiero-sdk-js/issues/2964

refactor: remove account creation in integration tests

---

src/exports.js
src/query/CostQuery.js
src/query/Query.js

Circular dependency workaround was breaking our webpack build and treeshaking code that was actually necessary. 
**Checklist**

fix: remove circular dependancy in dependencies

---

.github/CODEOWNERS

Remove `github-committers` team from codeowners file
**Related Issue(s)**:
Fixes #2990

chore: remove github-committers team from codeowners

---

src/account/AccountId.js
test/unit/AccountId.js

This PR improves the handling of account aliases and hollow accounts in the AccountId class by making the protobuf conversion more explicit and adding comprehensive test coverage.
- Add support for hollow account detection (num=0 with alias)
- More explicing protobuff conversion when:
1.  both `AccountId` `num` and `alias` are set
2. only `alias` is set
3. only `AccountId` `num` is set
Fixes #2982
**Notes for reviewer**: I am aware that there is some shorter syntax with the tenary operator but I don't think it's worth to safe a bunch of bytes at the cost of readability of the code. 
**Checklist**

fix: accountId instantiated from EVM address incorrectly sets evmAddress

---

examples/ecrecover-example.js
examples/ecrecover-mirror-node-example.js
examples/ecrecover_caller.json
examples/ecrecover_caller.sol
examples/package.json
examples/pnpm-lock.yaml

This PR adds an example which demonstrates how to sign and recover Ethereum addresses using the Hedera SDK, Ethereum-style signature hashing (EIP-191), and the ecrecover contract
https://github.com/hiero-ledger/hiero-sdk-js/issues/2598
Closes #2598

feat(examples): add ecrecover call

---

src/topic/TopicUpdateTransaction.js
test/integration/TopicUpdateIntegrationTest.js
test/unit/TopicUpdateTransaction.js

Fixes a bug in `TopicUpdateTransaction` related to the handling of `feeExemptKeys` and `customFees` properties when they are unset. Previously, the transaction would include empty arrays for these fields, unintentionally clearing existing values on the topic. This change ensures that unset properties are treated as `null`, preserving existing topic configurations.
- Ensures `feeExemptKeys` and `customFees` remain `null` in the object state when not explicitly set.
- `_makeTransactionData()` now excludes `feeExemptKeyList` and `customFees` from the transaction if they are `null`.
- Serialization and deserialization preserve `null` state for these fields.
- Added unit tests to verify correct behavior and prevent regressions.
Unintentionally resetting topic configurations is a critical …

fix(hip-991): null fees handling

---

src/Executable.js
test/unit/AccountInfoMocking.js

This PR fixes execution of `getReceiptQuery` and `getRecordQuery` that are single-node requests, meaning they rely on one specific node to succeed. If that node is unhealthy, these queries can fail with errors such as "Network connectivity issue: All nodes are unhealthy." To handle this, we retry the request up to 10 times before failing with a delay.
#2926 
**Checklist**

fix: Transaction receipt unhealthy error

---

src/topic/TopicCreateTransaction.js
test/integration/TokenUpdateIntegrationTest.js
test/integration/TopicCreateIntegrationTest.js
test/integration/TopicInfoIntegrationTest.js

This PR reintroduces and finalizes support for [HIP-1021](https://github.com/hashgraph/hedera-improvement-proposal/blob/main/HIP/hip-1021.md), which was previously reverted due to the changes not yet being live on mainnet.
Now that the feature is available on mainnet, we're enabling HIP-1021 with the required SDK logic.
**Related issue(s)**: https://github.com/hiero-ledger/hiero-sdk-js/issues/3042
Fixes # https://github.com/hiero-ledger/hiero-sdk-js/issues/3042
HIP-1021 introduces functionality that requires:
The autoRenewAccountId for TopicCreateTransaction to be automatically set to the fee payer if the user does not explicitly provide one.
This logic must be injected at the correct stage of the execution workflow, ensuring proper fee assignment and predictable behavior.
**Original …

feat: enable hip-1021

---

CHANGELOG.md
Taskfile.yml
package.json
packages/cryptography/Taskfile.yml
packages/cryptography/package.json
packages/proto/Taskfile.yml
packages/proto/package.json

- Support for HIP-1064 daily rewards https://hips.hedera.com/hip/hip-1064 This HIP proposes a reward mechanism that will incentivize nodes to remain active on the network. [#3099](https://github.com/hiero-ledger/hiero-sdk-js/pull/3099)
- NodeCreateTransaction `declineReward`: whether the node declines rewards
- NodeCreateTransaction `setDeclineReward`: update whether the node declines reward
- Added the `x-user-agent` header to all gRPC calls to enable SDK version tracking, following the approach outlined in [#3089](https://github.com/hiero-ledger/hiero-sdk-js/pull/3089)
- Included examples that demonstrate proper error handling in realistic, real-world scenarios, including how to manage network connectivity issues when interacting with a single node. …

chore(release): v2.64.4

---

examples/sign-tx-body-bytes-with-hsm.js
src/transaction/SignableNodeTransactionBodyBytes.js
src/transaction/Transaction.js
test/integration/TransactionIntegrationTest.js
test/unit/Transaction.js

This PR introduces support for external transaction signing using Hardware Security Modules (HSMs) in the JavaScript SDK. It provides a new API surface to expose canonical `bodyBytes` that are valid for signing, allowing signatures to be generated securely outside the SDK and injected back into the transaction. This feature is essential for enterprise and regulated environments where private keys must remain within secure hardware.
- Support for external transaction signing via HSM: Introduced `SignableNodeTransactionBodyBytes` and `signableNodeBodyBytesList` to enable enterprise users to extract canonical `bodyBytes`, sign externally (e.g., with an HSM or KMS), and inject signatures back into transactions securely. This improves SDK usability for high-security environments.
- New class …

feat: expose signable transaction body bytes for HSM signing

---

CHANGELOG.md
package.json
packages/cryptography/package.json

Stable release v2.65.1
-   Support for external transaction signing via HSM:
-   Introduced `SignableNodeTransactionBodyBytes` to encapsulate `nodeAccountId`, `transactionId`, and canonical `bodyBytes`.
-   Added `Transaction.signableNodeBodyBytesList()` API to return node-specific, signable transaction bytes for HSM workflows, enabling secure external signing and signature injection.
-   Improves usability in enterprise and regulated environments. [#3119](https://github.com/hiero-ledger/hiero-sdk-js/pull/3119)
-   Test coverage for HSM-based signing added to the JavaScript SDK, including usage examples. [#3119](https://github.com/hiero-ledger/hiero-sdk-js/pull/3119)
-   Added a library to determine key type and updated relevant files to use the correct key type …

chore(release): v2.65.1

---

src/EthereumFlow.js
src/EthereumTransaction.js

`setMaxGasAllowance` is defined in hbars, not tinybars.
N/A
Unit tests already consider those values as hbars, see: https://github.com/hiero-ledger/hiero-sdk-js/blob/9951a906c235628d74c1bb85f1f30a3d47092da8/test/unit/EthereumTransaction.js#L18 and https://github.com/hiero-ledger/hiero-sdk-js/blob/9951a906c235628d74c1bb85f1f30a3d47092da8/test/unit/EthereumTransaction.js#L46
**Checklist**

fix: setMaxGasAllowance is defined in hbars, not tinybars

---

examples/get-address-book.js
src/client/Client.js
src/client/NativeClient.js
src/client/NodeClient.js
src/client/WebClient.js
src/file/FileId.js
test/unit/FileId.js
test/unit/node/NodeClient.js

Adds persistent realm and shard according to https://github.com/hiero-ledger/sdk-collaboration-hub/pull/28
- `ClientConfiguration` type updated: The `Client` constructor now accepts `shard` and `realm` parameters directly.  
- `Client.forMirrorNetwork` now supports two additional arguments: `shard` and `realm`.
- When a custom network is provided in the `Client` constructor, the `shard` and `realm` values are now automatically inferred from the specified network.
- An error is now thrown if the nodes defined in a custom network are not all in the same shard and realm, enforcing consistency and preventing misconfiguration.
Fixes https://github.com/hiero-ledger/hiero-sdk-js/issues/3153
Notes for reviewer:
Checklist

feat: add shard and realm pesistence to the client

---

tck/methods/index.ts

This PR fixes redundant `glob` method.

chore(TCK): Glob method replacement

---

src/node/NodeDeleteTransaction.js
src/node/NodeUpdateTransaction.js
test/unit/NodeDeleteTransaction.js
test/unit/node/NodeUpdateTransaction.js

This PR adds SDK-level validation to ensure the `nodeId` field is explicitly set in both `NodeUpdateTransaction` and `NodeDeleteTransaction` before execution. Without this check, the `nodeId` defaults to `0`, which can dangerously affect node `0.0.3` if not intended.
Add support for ...
- Throws an error if `nodeId` is not explicitly set prior to calling `execute()`.
- Prevents unintentional updates or deletes to node `0.0.3` caused by default protobuf behavior.
- Added validation to `NodeUpdateTransaction` and `NodeDeleteTransaction` ensuring that `nodeId` is explicitly set before execution. This prevents accidental updates to node `0.0.3` due to protobuf's default `uint64 = 0` behavior. 
**Related Issues**:
https://github.com/hiero-ledger/hiero-sdk-js/issues/3181 …

fix: add validation for nodeId

---

.github/workflows/build.yml
.github/workflows/publish_release.yaml

This pull request introduces updates to the `.github/workflows/publish_release.yaml` file to support dual publishing for both `@hashgraph` and `@hiero-ledger` packages, as well as minor cleanup in `.github/workflows/build.yml`. The changes include adding environment variables, conditional logic for dual publishing, and new steps for handling `@hiero-ledger` package publishing. 
These changes collectively improve the release workflow by enabling dual publishing, enhancing flexibility with dry-run testing, and ensuring a clean and maintainable setup.
Fixes #3232
**Checklist**

chore: Add safety checks on JS dual publish changes

---

src/topic/TopicUpdateTransaction.js
test/integration/TopicUpdateIntegrationTest.js
test/unit/TopicUpdateTransaction.js

This PR aligns clear methods for array properties in `TopicUpdateTransaction` to other SDKs, making these methods actually remove the arrays from the network state.
This inconsistency was found via TCK testing
Related Issue #3240
**Checklist**

fix: Clear methods in `TopicUpdateTransaction`

---

.github/workflows/publish_release.yaml

This pull request updates the `publish_release.yaml` GitHub Actions workflow to improve usability and reporting. The main changes include simplifying the logic for enabling dual publishing and adding a step to generate a summary table of package versions and their publish status.
Workflow logic improvements:
* Simplified the `DUAL_PUBLISH_ENABLED` environment variable expression to remove the explicit comparison to `'true'`, making it more flexible and concise in both relevant jobs. [[1]](diffhunk://#diff-4f398b9d652dfd8c5f7eaa797dc903b64a3735a99002c81f795d877bc43b4ba8L37-R37) [[2]](diffhunk://#diff-4f398b9d652dfd8c5f7eaa797dc903b64a3735a99002c81f795d877bc43b4ba8L321-R333)
Reporting enhancements:
* Added a new step that generates a markdown summary table of package versions and whether …

ci(bug): Fix DUAL_PUBLISH_ENABLED checks

---

.github/workflows/build.yml
.github/workflows/common_js.yml
.github/workflows/pages.yml
.github/workflows/publish_release.yaml
.github/workflows/react_native.yml
package.json
tck/Taskfile.yml

Node.js 20 is approaching end of life, but we are allowing the community additional time to migrate to a more recent release but we won't be bumping to `engine` property in `package.json` as this might be a breaking change for users. CI tests will now be executed on Node.js versions 22 and 24.
#3242
**Checklist**

feat: bump node.js version in ci

---

src/LedgerId.js
src/contract/ContractCreateTransaction.js
src/contract/ContractDeleteTransaction.js
src/contract/ContractUpdateTransaction.js
src/encoding/hex.js
tck/methods/contract.ts
tck/methods/file.ts
tck/params/contract.ts
tck/response/contract.ts
test/unit/ContractDeleteTransaction.js

Implement Contract transaction for the TCK.
SDK changes:
- Makes `setStakedAccountID` and `setStakedNodeID` explicitly mutually exclusive. Setting one sets the other to null.
- Makes `setTransferAccountId` and `setTransferContractId` explicitly mutually exclusive. Setting one sets the other to null.
- Adds the ability to remove autorenew account in `ContractUpdate` via setting it to `0.0.0`
- Added check in `ContractCreateTransaction` to reject setting gas less than 0.
- Added validations in `hex.js` for decoding invalid hex strings.

feat(TCK): add contract transactions endpoints

---

.github/workflows/pr_check.yml

This pull request updates the GitHub Actions workflow configuration to use a different runner for the `title-check` and `assignee-check` jobs. The runner is changed from `hiero-network-node-linux-medium` to `hiero-client-sdk-linux-medium` to align with current infrastructure requirements.
Workflow configuration updates:
* Changed the runner for the `title-check` job in `.github/workflows/pr_check.yml` from `hiero-network-node-linux-medium` to `hiero-client-sdk-linux-medium`.
* Changed the runner for the `assignee-check` job in `.github/workflows/pr_check.yml` from `hiero-network-node-linux-medium` to `hiero-client-sdk-linux-medium`.

chore: Change runner type for PR checks to client SDK
